### ISSUE TITLE
For Launch

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#20]
## Site refactor
- [x] New front page - #22 
- [x] Move data catalog - #21 
- [x] standards page - #36
- [x] tools page - #37
### Integration
- [x] Load in sqlite - #25 (sqlite)
- [x] Load into postgresql - #26
- [x] Google spreadsheet load #24 
- [x] R load - #23 

Wherever possible put in gists or similar so easy to embed and update
### Example Data
- #35 - all example data
### User Story Examples
- [ ] Deflation
- [ ] House prices on GDP, long term interest rates, population - #32
