### ISSUE TITLE
Define standards for frontmatter

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/frictionlessdata.io#422]
Frontmatter is the metadata in pages. It is an essential "API" between content authors and the theme designers. Thus, defining this frontmatter is crucial.

Purpose of this issue is to define frontmatter for main categories for pages:

* jobs
* products
* blog

This issue was previously part of https://github.com/frictionlessdata/project/issues/402 and https://github.com/frictionlessdata/project/issues/417.

## Acceptance

* [x] Frontmatter for blog posts
* [x] Frontmatter for jobs to be done pages
* [x] Frontmatter for product pages
* [x] Made changes to existing pages inline with these new specs
* [x] Docs/guidance for people wanting to contribute to the website on use of frontmatter in README or contributing.md.

## Tasks

* [x] Define standards for each of the page types
  * [x] For blog posts
  * [x] For jobs to be done
  * [x] For product pages
* [x] Implement in the theme @monikappv 
  * [x] Change frontmatter for one page of each type
    * [x] blogs - https://github.com/frictionlessdata/website-v2/commit/3be8585eb2f962f73ccbab755ff9ab371cf6e366 
    * [x] jobs https://github.com/frictionlessdata/website-v2/commit/e420673cb35e0e223bd3b0502bf3534738a78c14
    * [x] products https://github.com/frictionlessdata/website-v2/commit/b25bf6c28d4e5bdbd6586da0b27ea5f4fe99ed63
  * [x] Update the theme
  * [x] Set page title from frontmatter title
  * [x] Do excerpt / description work https://github.com/frictionlessdata/website-v2/commit/c09f43a00cfc1471d80207531ca10867f128b65d
* [x] Make changes to all existing pages inline with these new specs
* [x] Document standards in a Markdown file. My (@irio) suggestion is to have them in a `CONTRIBUTING.md` file. As in https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file.

### Common

This frontmatter is common to all pages and maybe used in any of them. Every page MUST have a title. All other values are optional. 

```md
---
title: Data Package
tagline: # one sentence description
description: # an exerpt or description
image: /data-package-diagram.png
layout: product | job [| blog]
---
```

### Page titles

Our convention is that page titles are set in frontmatter not in markdown. This allows them to be styled different etc.

:white_check_mark: 

```md
---
title: My Page
---

This page is about X ...
```

:x: 

```md
# My Page

This page is about X
```

#### Page Excerpts (go to description)

NB: if excerpt and no description => move excerpt to frontmatter description

For theming: always use frontmatter.description (never use $page.excerpt ...)

https://vuepress.vuejs.org/theme/writing-a-theme.html#content-excerpt

```javascript=
if (!$page.frontmatter.description && $page.excerpt) {
  $page.frontmatter.description = $page.excerpt;
} else {
  $page.frontmatter = ''
}
```

### Blog posts

```
---
category: case-studies | grantee-profiles | pilots | grantee-profiles-2019
date: # date of publication in yyyy-mm-dd format
author: (?)
tags: 
---
```

TODO: author

Use  or "intro" TODO: look this up and put link ... 

Changes:

* summary => description
* intro => 

When category == "case-studies" | "pilots"

```
interviewee: 
subject_context: 
```

When category == "grantee-profiles"

```
github: 
twitter:
website: 
```

NB: currently most of them have title, category, date, summary and image.

### Jobs

```md
tagline:
pain:
context: (?)
hexagon:
```

### Product pages

```md
hexagon:
github: # list of github repos ...
```

**Comment by monikappv** [comment]
FIXED.
