### ISSUE TITLE
[v2] Implement Redirects for v1 URLs

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#423]
## Acceptance Criteria
* [x] The URLs of the old website redirect to new URL links

## Tasks

- [x]  Identify how to do redirects Seems vuepress does this centralized rather than per page and in JS config. See vuejs/vuepress#239. There is also a plugin https://vuepress.github.io/en/plugins/redirect/#installation - seems a little confusing but think it would do the job and can do bulk redirects from a sub-url
- [x]  Make list of all redirects (use spreadsheet)
- [x]  Implement that
- [x]  Test it (by hand? or use automated testing if done above) (Done Manually)

## Implementation

Created an `enhanceApp.js` file along with `config.js` for the redirects. Didn't implement it via plugin.

* I(@MuhammadIsmailShahzad ) took old and new urls the list from the spreadsheet --https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#gid=710398809
* Saved them in a list and added them to router
* Tested them manually

## Writing code for redirects
* I got the list of old(`page`) and new routes(`Destination in new website`) from this spreadsheet -- https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#gid=710398809
* Created a `enhanceApp.js` file in the directory `site/vuepress` -- [enhanceApp.js](https://github.com/MuhammadIsmailShahzad/website-v2/blob/master/site/.vuepress/enhanceApp.js)
* Saved the list for old and new routes in two different variables i.e `oldUrl` and `destinationUrl`
**NOTE : The lists for old and new routes are hardcoded**
* I added the combined list i.e `redirectList` to the `router` by using `router.addRoutes(redirectList)`

## TESTS
* Followed manual testing by picking random urls
    * Test failed for `/software/`
        * restarting the website
        * SUCCESS its redirecting to `/products/` :+1: 
    * `/docs/joining-tabular-data-in-python/` should redirect to `/blog/2018-04-05/joining-tabular-data-in-python/`
        * Result: SUCCESS :+1: 
    * `/articles/university-of-pittsburgh/` should redirect to `/blog/2017-12-15/university-of-pittsburgh/`
        *  Result: SUCCESS :+1:
    * `/articles/open-referral/` should redirect to `/blog/2019-07-09/open-referral/`
        *  Result: SUCCESS :+1:
    * `/articles/open-knowledge-greece/` should redirect to `/blog/2017-10-27/open-knowledge-greece/`
        *  Result: SUCCESS :+1:

## Flaw in previous approach

* I just found out that as I am using two different lists for old and new links it can be a bit problematic when updating these links as one must make sure that the related links from both the lists are at the same indexes in both variabls.

### Solution (Fixed)

* As we are already hardcoding the old and new links in the variables, we can just add them directly to the routes like this--- This would eliminate the need of keeping track of indexes of the variables.
    ```javascript
  const redirectList = [
  {
    path: "/software/",
    redirect: "/products/"
  },
  {
    path: "/articles/",
    redirect: "/blog/"
  }] 
  export default ({ router }) => {
  router.addRoutes([redirectList])
  } ;


    ```

**Comment by rufuspollock** [comment]
@MuhammadIsmailShahzad is this done? If so, please close as per structure in http://handbook.datopian.com/issues-tasks/#closing-issues

**Comment by ismail-shahzad** [comment]
FIXED. See commit https://github.com/frictionlessdata/website-v2/commit/39ba547c3b091901b3e1374de5271f0adb66a995 and staging  https://github.com/frictionlessdata/website-v2/pull/18

**Comment by lauragift21** [comment]
>## TESTS
* Followed manual testing by picking random urls
    * Test failed for `/software/`
        * restarting the website
        * SUCCESS its redirecting to `/products/` :+1: 
    * `/docs/joining-tabular-data-in-python/` should redirect to `/blog/2018-04-05/joining-tabular-data-in-python/`
        * Result: SUCCESS :+1: 
    * `/articles/university-of-pittsburgh/` should redirect to `/blog/2017-12-15/university-of-pittsburgh/`
        *  Result: SUCCESS :+1:
    * `/articles/open-referral/` should redirect to `/blog/2019-07-09/open-referral/`
        *  Result: SUCCESS :+1:
    * `/articles/open-knowledge-greece/` should redirect to `/blog/2017-10-27/open-knowledge-greece/`
        *  Result: SUCCESS :+1:

Hi @MuhammadIsmailShahzad When you worked on this did you by any chance check that it works after `build` and not in `development`? I'm asking because of https://github.com/frictionlessdata/project/issues/448

**Comment by ismail-shahzad** [comment]
@lauragift21 I dont remember much but I think I might have tested these during development on my machine. 
But going through the commit history, I see commits like fix broken links, etc. So this might be working after `build` too. 
![Screenshot from 2020-04-02 00-20-48](https://user-images.githubusercontent.com/57398621/78177688-ee875c00-7477-11ea-97ef-8960e214d470.png)

**Comment by lauragift21** [comment]
Thanks, I've fixed the issue I had. @MuhammadIsmailShahzad
