### ISSUE TITLE
Create semantically correct links in the jobs to be done diagram in the new website

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/frictionlessdata.io#424]
As stated in the issue for creating the diagram, currently, the anchors just exist in Javascript. People using screen readers are the ones most affected, but also it impacts everyone. For instance, browsers don't show the destination of the link while hovering a hexagon. Thus, it may not be top priority, but it's still very important to be done.

In the initial analysis made by @MuhammadIsmailShahzad and I, we couldn't easily figure out a way to do so.

## Acceptance

* [ ] We have semantically correct anchors in the diagram.

## Tasks

* [ ] Research/read the source code of svg.js and honeycomb-grid to understand if it's really a feature not supported.
* [ ] Read the source code of these libs to understand how to extend them.
* [ ] Possibly open an issue in the most appropriate project asking for help.
* [ ] Implement the change.

## References

https://alligator.io/svg/hyperlinks-svg/

**Comment by rufuspollock** [comment]
DUPLICATE / MERGED. Merged into root issue #421
