### ISSUE TITLE
[v2] Misc final fixes

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#428]
Misc final fixes for v2 site - epic in #415 

## Acceptance

N/A

## Tasks

* [x] final 4-5 pages to migrate ..see https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=710398809 @rufuspollock **DONE: last few pages moved over or redirect done** 
* [x] Review content and tidy blog #435 @lwinfree 
* [x] Front page looks "done" 
  * [x] 2 links one to guide (Get Started) and video (like vuejs)
  * [x] (Bonus) switching text in main tagline ... data integration / wrangling / workflows / science / work
    * [x] :clap: good job. A few improvements. Should loop. Should start with default text and *then* overwrite. - Done (Tried starting with default text but can only specify text that needs to be changed I'll explain more during standup)
  * [x] color alternating sections (may need to revert a bit to tailwind setup?)
  * [x] Tidy up - Make stuff look tidier e.g. for researchers ... @gift
* [x] Tidy the footer (?) e.g. smaller font, footer across whole page
  * [x] home page footer
  * [x] footer when sidebar provided
* [x] make sure the website is responsive @lauragift21 
NB: footer and tools section outstanding
* [x] Remove copyright from footer on *front page* - just remove from README.md is all that is needed @rufus
* [x] Make callout buttons round @monikappv 
* [x] Check with @monika how we did page description / excerpting (grepping the code i can't see us generically extracting this for all pages ... but the frontmatter instructions talk about this) - see section on Page Excerpts in https://github.com/frictionlessdata/project/issues/422 (and my comment on your commit)
* [x] @irio - Consolidate Data Package and Table Schema pages https://github.com/frictionlessdata/project/issues/433

### Future

* [x] Tweak the logo (with text and thicker f)
* [x] (Future) products => tools in url

**Comment by rufuspollock** [comment]
FIXED. All done. Remaining future items moved to https://github.com/frictionlessdata/project/issues/446
