### ISSUE TITLE
Sidebar for the Specs Site

### ISSUE THREAD

**Issue by nirabpudasaini** [frictionlessdata/frictionlessdata.io#429]
Subissue for frictionlessdata/project#413

Currently the sidebar shows only the h2 and h3 headers as navigation elements for each page. This should be the case for the specs pages but the homepage should have a different sidebar. It should match https://web.archive.org/web/20170627080529/http://specs.frictionlessdata.io/ where the sidebar not only shows the home page elements but also all the available spec pages. 

## Acceptance
* [x] The sidebar for the specs home page is similar to https://web.archive.org/web/20170627080529/http://specs.frictionlessdata.io/
* [x] All the other pages have just their individual page elements in the sidebar.

## Tasks
* [x] Edit conif.json to have get the desired sidebar for the frontpage
* [x] Add 'sidebar: auto' to all other pages where the sidebar is not necessary. 

## Analysis
* Veupress default theme can be configured to have grouped sidebar https://vuepress.vuejs.org/theme/default-theme-config.html#sidebar-groups which is suitable to build our homepage sidebar. 
![homepage](https://user-images.githubusercontent.com/3871904/75230049-cc852480-57bb-11ea-9bf6-0a9720947a75.PNG)

* Adding 'sidebar: auto' to the frontmatter of the page will override the default sidebar and show the sidebar with only the page elements for that page. 
 

---

Please preserve this line to notify @lwinfree (lead of this repository)
