### ISSUE TITLE
[epic] Guide to Frictionless Data

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#430]
We want a single guided entry point to Frictionless Data (Framework) - in keeping with our simple, accessible, progressive philosophy!

Job Story: When I first come to Frictionless Data (or am at early stages) I want a guide that introduces me to the framework and how to use it so that I can get started quickly (and decide if this is for me). 

Inspiration is VueJS and their excellent guide: https://vuejs.org/v2/guide/

This follows on from (and is motivated by and, in a way, part of) the major website and comms work https://github.com/frictionlessdata/project/projects/2 A major motivation for that work is that Frictionless Data (as a project) is confusing (overwhelming) and dispersed. Thus, a clear entry point and guide would be really valuable.

At the same time, we want to avoid that piece of work becoming "never-ending" thus we have separated this piece of work out.

## Design

The big challenge here will be to work out a sensible "linear" (or minimally branching) path into Frictionless Data. 

## Acceptance

* [ ] Guide section exists
* [ ] A step by step incremental introduction to the patterns and (some of the tools)
  * [x] Table Schema
  * [ ] Data Resource
  * [ ] Data package
  * [ ] Data Flows (?)

## Tasks

* [ ] Plan of work: **Good overview in this coggle from (?) June with @irio 
 and @rufuspollock https://coggle.it/diagram/XrGHgfimBfndKRzN/t/frictionless-data-guide**
* [ ] Catalog and analyse existing relevant content for what we can reuse e.g. Field Guide, datahub.io/docs/ #431 
* [x] Stub the guide (even if just links atm) - **see http://frictionlessdata.io/guide/**
  * [x] Intro section (cf vuejs) - **see http://frictionlessdata.io/guide/**
  * [x] First example section e.g. re Table Schema **see http://frictionlessdata.io/guide/**
* [x] Plan out the guide overall **See WIP here https://hackmd.io/Nhbzig5UTbKBxCNQWMsong?view** also see issue #440 
* [x] Table and Table Schema section ...  #441

---

## Rufus notes (~ May 2020)

This is the plan / outline for the Guide as a whole.

```mermaid
graph TD

a[Declarative Data + Atomic Tools - the unix way]

table[A Table]
ts[Table Schema]
validation[Validation]

dr[Data Resource]
dp[Data Package]
csvddf[CSV Dialect]
tabulator[Tabulator]
beyondtabular[More than Tabular Data]
view["(Pre)View"]
csvtoxls["CSV to Excel (with correct types)"]
philosophy[Philosophy<br/>Explaining the implicit/explicit background]
publishing["Publishing Data(sets)"]
sqlite[Load to SQLite]

a --> table
a --> philosophy

subgraph "Table Schema"
  table --> ts
  ts --> validation
  validation -. should this be here or later .-> tabulator
end

subgraph "Data Resource"
  tabulator --> dr
  dr --what about csv with tabs--> csvddf
  csvddf --> view
  view --> csvtoxls
end

csvtoxls --> beyondtabular
publishing --> beyondtabular

fk[Table Refereneces and Foreign Keys]
postgres[Load to Postgres]

subgraph "Data Package"
  csvtoxls --> dp
  dp --> sqlite
  sqlite --> fk
  fk --> postgres
  postgres --> publishing
end

flowsconcept[Flows Concept]

subgraph Flows
  publishing --> flowsconcept
  flowsconcept --> more[Much more ...]
end
```

## Questions

* Philosophy esp re declarative: e.g. there are tools out there that will do csv dialect inference, or type inference or ... built in to the tool (csvkit, pandas etc). And they are great. However, there are some limitations that can be summarized in terms of a) implicitness (or lack of declaractiveness) b) monolithicness (and hence problems scaling up and down).
  * implicitness: basically these tools do infer something pretty like table schema or a csv dialect definition but they are "internal" or "implicit". As a result its a) difficult to get that information out (say, if you want to correct it or pass it somewhere else) and b) cumbersome to pass that information if you can at all (it's lots of different options)
  * monolithicness (bigger issue): pandas is an amazing tool. It also requires numpy just to run. Nowadays i often see starting data scientists using pandas to build simple data wrangling pipelines (e.g. load this csv, delete this row etc). This is quick but it also means that you now need to install pandas just to do that (and what happens if you want to start doing integrated testing, you are now installing a very substantial lib every time etc). What you would like is something that just did type inference or dialect inference but which you then compose with other tools to build more complex functionality (this is the zen of unix again). This is scaling down.

    There's also scaling up: pandas is awesome but it doesn't do everything. Suppose you now want to use some other tool and you want to pass your data across (as csv). You will need to share some basic info about that data e.g. the schema, dialect etc! Wouldn't it be nice if you could do that in a standard way ... and all in one (not 3-4 different objects but one combined object) ... enter Table Schema, Data Resource etc.
* What's the motivation for data resource? Do we need one? What can we do with a data resource?
  * csv dialect ... (together with table schema)
  * some metadata
  * One motivation is the simple "2 arguments" one. Data Resource is basically Table Schema + a file pointer. It's all in one.

  So instead of:

  ```
  validate --schema tableschema.json helloworld.csv
  ```

  I can do:

  ```
  validate dataresource.json
  ```

  Also, i can add additional information e.g. CSV Dialect, Table information ... (but why ...)

  Maybe convenient bundling is enough. .... Or we just introduce data resource with data package ...
* Can we do validation in javascript?
* do we want to mention problem of CSV not having types? (or is it enough just to do validation)
* 3 types of thing
  * Concept e.g. a Table
  * Spec / Pattern e.g. Table Schema
  * Tool / doing something e.g. GoodTables

## Stuff to do / Jobs to be done (i.e. useful things you could use frictionless to do)

* pushing e.g. to db
* inference (of table schema and package)
* displaying / presenting data
* views (graphs etc)
* flows (? - this is a whole section)
* pulling e.g. from a spreadsheet
* publishing
* Using data package: let's convert a google spreadsheet into a database
  * let's convert sqlite to postgres (?)

## Random Thoughts - Bet on Javascript

[![](https://i.imgur.com/u0hcexu.png)](https://brendaneich.github.io/ModernWeb.tw-2015/#74)
_Brendan Eich_

### Premises

* Frictionless Data already has a community with people maintaining tools in a few languages.
* There are many people in the data industry that already heard about Frictionless Data. Some had good experiences and remain using our tools; others didn't and stopped using/never used them.
* There are no good tools for working with data processing (dataframes included) in Javascript.
* It's really easy to start programming in Javascript.
* Javascript is the most popular language for people to start programming nowadays.
* Javascript is a popular language for microservices (together with Go and Python).
* Javascript is a popular language for serverless applications (together with Go).

### Assumptions

* The community will probably continue to maintain these tools in other languages.
* There are always people learning to work with data. It may be easier to convince people who doesn't have favorite tools/paradigms yet.
* To get attention from people who heard about Frictionless Data in the past and didn't have a good experience, it's easier if there's a new offering or perceived focus.
* Javascript represents a market gap in the data industry. Not necessarily a good or the best one, but certainly one.
* Language-wise, Python does not have things that don't exist in Javascript. The difference is in libraries and the ecosystem.
* In Javascript, it's much easier to integrate with tools providing user-interaction (because it's already in the browser langauge).

Irio - As a Data Engineer, I wouldn't necessarily prefer Javascript, but I could be convinced with good arguments and better tooling.

**Comment by lwinfree** [comment]
@rufuspollock this is the same as the docs work that myself & @roll have been working on, yes?

**Comment by rufuspollock** [comment]
@lwinfree i think definitely connected though i imagined as more complementary - do you guys have an outline of the docs work somewhere in an issue so we could work that out more clearly? (ie. what you guys are planning there vs what is here)?

**Comment by lwinfree** [comment]
Just noting for transparency (and for my brain 🙃 ) that Rufus, Evgeny, and I (and potentially others?) will map out what the guide & docs will look like & then work to make it happen together.

**Comment by rufuspollock** [comment]
@lwinfree yes, perfect we should have a sync asap. In the meantime can you / @roll create an issue in this repo that provides an overview of both the plan and the current state of play on the docs? That will help me get myself up to speed.

**Comment by lwinfree** [comment]
@rufuspollock yes it's on my Monday to do list now!

**Comment by lwinfree** [comment]
@rufuspollock here's our old [working doc](https://docs.google.com/document/d/1qtVds63PwsRqFhm209jdJk0e-QZ3C_XgK7yB-nP6c-0/edit) (hasn't been updated in a while since we paused working on it)

Overall, the plan for docs was to make sure they are:
1) in 1 place
2) organized in a logical way
3) searchable

More specifically, at [https://docs.frictionlessdata.io/](https://docs.frictionlessdata.io/#/) we had gathered all the existing docs & started organizing them. 

Outstanding todo's include
- making sure everything from frictionlessdata.io/docs is captured on the new site
- testing all the code in the examples to make sure it works (note: some of this is done)
- fleshing out the developer/contributor sections
- writing a really nice overview *--> Note: I think this is the aim of Rufus' idea for the guide?*

Existing questions include:
- should the docs be on the main FD site, or on a separate site (like the specs site)
- what information remains on github readmes?
- we need to make sure we are thinking about each piece of documentation with respect to its function (eg is it a tutorial, how to, explanation, or reference - this is helpful: https://www.divio.com/blog/documentation/)
- what goes on the "guide" and what goes in the docs

CC @roll

**Comment by lwinfree** [comment]
closing as this has now been incorporated into the main site (introduction) and framework docs
