### ISSUE TITLE
Catalog and analyze existing guide-related content

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#431]
## Catalog and analyze existing guide-related content #431
We want to locate, catalog and analyse existing material that would be relevant for the (new) guide #430 

In order of priority:

* Field Guide https://frictionlessdata.io/field-guide/ (moving to blog)
* FD related stuff on https://datahub.io/docs/ - https://github.com/datopian/datahub-content
* Old https://frictionlessdata.io/docs/

## Acceptance

* [x] A new sheet here https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=23938125 listing all the main relevant documentation
  * [x] URL
  * [x] Title / one sentence
  * [x] Description (sentences / paragraph)
  * [x] Brief analysis of relevant content + recommendation on whether to ignore, reuse etc
  * [x] % for quality
  * [x] % for reusablility

## Tasks

* [x] Review the field guide
* [x] Review datahub.io/docs
* [x] Review frictionlessdata.io/docs
* [x] Rework description and make it more informative
* [x] Add more detail to the comments - why it is important and what key part to reuse.
* [x] Add % for quality
* [x] Add % for reusabality
* [x] Draw the diagram in coggl or miro or mermaid of fd docs / field guide

## Analysis
- @Gift and @Mario currently working on this task.
- @Mario created a mind map that would help us visualize content and decide what should be reused and omitted. 

![mermaid-diagram-20200312125659](https://user-images.githubusercontent.com/17781315/76519327-0d8a6380-6461-11ea-990a-0c70044ecd31.png)

**Comment by rufuspollock** [comment]
@lauragift21 could you take this on - you can also involve Mario.

**Comment by lauragift21** [comment]
Yeah sure @rufuspollock. I will work on this after I wrap up what I'm currently working on which is making the site look responsive.

**Comment by lauragift21** [comment]
FIXED. Mario and I reviewed and analyzed the guides and created this [spreadsheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=23938125) to document the relevant content that we can reuse.

**Comment by lauragift21** [comment]
@rufuspollock I fixed your comments on the document. Overall changes added include:
- a clear description of the document
-  % for quality
- % for reusability
- detailed comments

I've updated the issue to reflect this change as well. Kindly review and let me know the next steps.

**Comment by lwinfree** [comment]
Hi @lauragift21! There are a few other documents that are missing from this analysis, mainly located in the old labs blog (https://okfnlabs.org/). Here's a list of the ones that I think are missing from your current spreadsheet. Do you think you could go through these ones too and do the same analysis? Your analysis is really helpful, so it would be awesome to have it for these too. Some of this content is pretty repetitive and old, so it would be helpful to tag that. Thanks!

- [x] https://okfnlabs.org/blog/2018/08/29/data-factory-data-flows-introduction.html
- [x] https://okfnlabs.org/blog/2018/08/30/data-factory-data-flows-tutorial.html
- [x] https://okfnlabs.org/blog/2018/10/18/announcing-datapackage-pipelines-v2.html 
- [x] https://okfnlabs.org/blog/2018/05/07/datapackages-in-clojure.html
- [x] https://okfnlabs.org/blog/2018/04/28/datapackages-in-java.html
- [x] https://okfnlabs.org/blog/2018/02/16/datapackages-in-go.html
- [x] https://okfnlabs.org/blog/2019/08/01/intro-statistics-datapackage-gonum.html
- [x] https://okfnlabs.org/blog/2018/02/14/datapackages-in-r.html
- [x] https://okfnlabs.org/blog/2016/07/14/using-data-packages-with-r.html
- [x] https://okfnlabs.org/blog/2017/12/21/bootstrapping-data-standards-with-frictionless-data.html
- [x] https://okfnlabs.org/blog/2017/11/29/validating-scraped-data-using-goodtables.html
- [x] https://okfnlabs.org/blog/2016/08/01/using-data-packages-with-pandas.html

**Comment by lauragift21** [comment]
Yes, thanks for pointing these out @lwinfree. I will do an analysis of these content as well.

**Comment by lauragift21** [comment]
Done. @lwinfree I added analysis for content you pointed in the spreadsheet. https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=23938125

**Comment by lwinfree** [comment]
thank you @lauragift21 !

**Comment by lauragift21** [comment]
DONE. We've collected and analyzed existing content here https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=23938125
