### ISSUE TITLE
[v2] Switch over the DNS (and do any Cloudflare level redirects)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#432]
Switch over to the new site 😄

## Acceptance

* [x] Existing fricitionlessdata.io is at old.frictionlessdata.io
* [x] current next.frictionlessdata.io is at frictionlessdata.io

## Tasks

* [x] Add permanent redirects (301 HTTP status) in fd.io to new locations ...  - ~~should be part of #423~~ **turns out you can't do this in Vue [^why] so we have to implement this at cloudflare level** @amercader  @lwinfree 
  * [x] /specs/* => specs.frictionlessdata.io/*
  * [x] /schemas/* => specs.frictionlessdata.io/schemas/
* [x] Add old.frictionlessdata.io to cloudflare DNS pointing to this github @amercader @lwinfree 
* [x] Change in `website-v2` repo CNAME to `frictionlessdata.io` @lauragift21 
* [x] ~~Change CNAME in `website` repo to old.frictionlessdata.io @lauragift21~~ Old FD site is hosted in S3, already done

**Comment by roll** [comment]
@amercader 
It looks good as far as I can see but it makes sense to wait Monday before pulling the trigger

Also, I think it would be much better to manage all the redirect on the vuepress level for flexibility and speed of fixing problems

**Comment by roll** [comment]
> Also, I think it would be much better to manage all the redirect on the vuepress level for flexibility and speed of fixing problems

I mean the subdomains should be redirected on Cloudflare level for sure. But managing individual page redirects will be much better to manage in the codebase

**Comment by amercader** [comment]
@rufuspollock 
> Add old.frictionlessdata.io to cloudflare DNS pointing to this github @amercader @lwinfree

What repo is that? I assume is not this one as there is no gh-pages branch

**Comment by rufuspollock** [comment]
@roll all the redirects *are* done in the local codebase. the redirects here are the ones that *have* to happen in cloudflare (see comment in the description!)

> > Add old.frictionlessdata.io to cloudflare DNS pointing to this github @amercader @lwinfree
>
> What repo is that? I assume is not this one as there is no gh-pages branch

@amercader you'd cname to frictionlessdata.github.io i believe (as per normal).

> It looks good as far as I can see but it makes sense to wait Monday before pulling the trigger

@roll @amercader can't this happen today? these changes in cloudflare are non-breaking - the specs website is operational for weeks 😉

**Comment by roll** [comment]
I see my bad. My focus is disordered as we're preparing to quarantine 

I think we need to do the switch when both I and Adria (and maybe Lilly) are online to assist in real-time in case of any problem

**Comment by amercader** [comment]
@lwinfree @rufuspollock @roll As of now we've done

* Set up https://old.frictionlessdata.io
* Redirects for `/specs/`
* Redirects for `/schemas/`

![Screenshot_2020-03-30 Page Rules frictionlessdata io Account Cloudflare - Web Performance Security](https://user-images.githubusercontent.com/200230/77907145-69d6eb00-7289-11ea-8ba0-f3741d9ee39c.png)

I'm holding in updating the records for the main site because the CNAME file is not updated there [AFAICT](https://github.com/frictionlessdata/website-v2/blob/gh-pages/CNAME). When you are ready on your end let me know, so we don't have downtime.


Please validate all these and let me know if they look good

**Comment by lauragift21** [comment]
@amercader I've just updated the CNAME on the main site.

**Comment by amercader** [comment]
Thanks @lauragift21 , the DNS records are now updated

**Comment by roll** [comment]
@lauragift21
My quick search for broken links:

https://frictionlessdata.io/blog/data-package	
https://frictionlessdata.io/docs/tabular-data-package/
https://frictionlessdata.io/docs/tabular-data-package/	
https://frictionlessdata.io/software/	
https://frictionlessdata.io/articles/	
http://frictionlessdata.io/blog/data-package
http://frictionlessdata.io/website-v2/	
http://frictionlessdata.io/website-v2/about/	
http://frictionlessdata.io/website-v2/specs/	
http://frictionlessdata.io/website-v2/blog/2018-03-07-well-packaged-datasets/	
http://frictionlessdata.io/website-v2/specs/table-schema/	
http://frictionlessdata.io/website-v2/specs/profiles/	
http://frictionlessdata.io/website-v2/specs/data-package/
http://frictionlessdata.io/website-v2/specs/tabular-data-package/	
http://frictionlessdata.io/website-v2/specs/fiscal-data-package/	
https://frictionlessdata.io/articles/open-knowledge-greece/	
https://frictionlessdata.io/blog/2017/12/19/dm4t/packagist.io	
https://frictionlessdata.io/user-stories/	
http://frictionlessdata.io/blog/2017/12/19/dm4t/packagist.io	
https://github.com/frictionlessdata/website/edit/master/blog/2018-03-07-well-packaged-datasets/README.md	
http://frictionlessdata.io/user-stories/	
http://frictionlessdata.io/docs/tabular-data-package/	
https://fgrow.friresearch.ca

**Comment by roll** [comment]
@lauragift21 
http://specs.frictionlessdata.io/ - Table Schema is missing at the left

**Comment by lauragift21** [comment]
@rufuspollock @roll will look into these and fix asap.

**Comment by roll** [comment]
Hi @lauragift21,

I received an email yesterday about https://old.frictionlessdata.io/field-guide/ - some person was reading it but it's not available anymore. I sent him the link above for now. But flagging it

**Comment by lauragift21** [comment]
Yes, thanks for pointing it out @roll. I'm looking into it here #448

**Comment by lauragift21** [comment]
@roll I've fixed the redirect issue on the site and tested out the broken links of which most of them now work. AFAIK some of the links have an additional `/website-v2` which will always return 404 because it's a wrong link.

**Comment by roll** [comment]
@lauragift21 
Awesome

BTW these website-2 links leak somewhere because it was found by a broken links checker

**Comment by rufuspollock** [comment]
FIXED. DNS switch happened with redirects.

@lauragift21 can you open a new issue for the broken links if that is still outstanding. And generally you can be proactive to close issues that are complete so that they don't clog up the repo.

**Comment by lauragift21** [comment]
Sure @rufuspollock. I've fixed the broken links.
