### ISSUE TITLE
Refactor Data Package and Table Schema Product pages to be about tooling (not the pattern)

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/frictionlessdata.io#433]
At this moment, we have the multiple pages talking about the same thing. The proposal is to consolidate them to a state good enough for release.

For instance, all of the following introduce Data Packages:

* https://next.frictionlessdata.io/data-package/
* https://next.frictionlessdata.io/products/data-package/
* https://next.frictionlessdata.io/guide/

## Acceptance Criteria

* [x] `/guide/` should be the main call to action from the home page. Content should reflect that.
* [x] **Data Package** - `/data-package/` should talk about the philosophy.
* [x] **Data Package** - `/products/data-package/` should talk about tooling.
* [x] **Table Schema** - `/table-schema/` should talk about the philosophy.
* [x] **Table Schema** - `/products/table-schema/` should talk about tooling.

## Tasks

* [x] Review guide to know how other pages should be.
* [x] Review `/data-package/`.
* [x] Review `/products/data-package/`.
* [x] Review `/table-schema/`. **DONE in https://github.com/frictionlessdata/website-v2/commit/71007444192c3e198cc7da30109e6a9ff0e35225**
* [x] Review `/products/table-schema/`. **DONE in https://github.com/frictionlessdata/website-v2/commit/71007444192c3e198cc7da30109e6a9ff0e35225**
* [x] Get libraries and code examples for `/products/data-package/`. **DONE in https://github.com/frictionlessdata/website-v2/commit/4475f65cfab324cca7a1b9f594cce28777f7383f**
* [x] Get libraries and code examples for `/products/table-schema/`. **DONE in https://github.com/frictionlessdata/website-v2/commit/71007444192c3e198cc7da30109e6a9ff0e35225**

---

Raw issue from HackMD:

```
* [ ] @irio - Table Schema product page is Table Schema libs (tools)
  * Currently spec/ideas ... and that has moved to /table-schema/ and guide stuff
  * We want to repurpose this page to be able the libraries / tools for table schema
* [ ] @irio - Data package product pages is Data package libs / tools
  * Ditto (but /data-package/ and guide)


# Data Package Tooling

Brief description of what is a data package. Read more on /data-package/ oer the guide ...

## Libraries

We have libraries for using and working with data packages in all the major languates

* R [link to github or wherever]
* ...

## Tools

* Data Package creator
* Tabulator (??) => another page or github

## Examples

[no need to make the examples interactable for this delivery]

---python
Load a data package

---

---r=

---
```

**Comment by Irio** [comment]
For Table Schema, I've tried to follow a format that can be replicated in Data Package pages, too.

Here's the /product/table-schema page now:

![screencapture-localhost-8080-products-table-schema-2020-03-02-12_34_12](https://user-images.githubusercontent.com/667753/75673072-60eefb80-5c82-11ea-80cb-c5cbe26eecbd.png)

**Comment by Irio** [comment]
DONE. The Data Package Tools page is currently in master like this:

![screencapture-localhost-8080-products-data-package-tools-2020-03-04-11_58_35](https://user-images.githubusercontent.com/667753/75873075-9b39d380-5e0f-11ea-84cb-ee16b272a65c.png)
