### ISSUE TITLE
How to have Live Examples in the Guide

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#434]
We would like to have live examples in e.g. Python, Javascript, R (?) etc.

## Acceptance

* [x] Have identified a standard way to create, maintain and embed these examples
* [x] Have examples in Python, Javascript (maybe R and Ruby)
-  **Python example in Repl.it https://repl.it/@lauragift21/data-package-py** 
-   **JavaScript example https://repl.it/@lauragift21/data-package-js** 
-   **Ruby example https://repl.it/@lauragift21/data-package-ruby**

## Tasks

* [x] Read about how to do research http://handbook.datopian.com/dojo/research/  - **Done - Read and watched the video and now working towards researching options for online code platforms.**
* [x] Find existing options for creating and running code online on e.g. jupyter notebooks, repl.it, runkit.com, etc - **Done - After doing a breadth-first search, I found a couple of platforms that can be useful for our use-case my next steps will be doing an in-depth look at each of the platforms and comparing each one based on what we need it for (ability to have live code examples in diff languages). [Here's my scratchpad for collecting info on this issue](https://hackmd.io/Z9AcvLCrT1W__ISoI2NshA?both)**
* [x] identify criteria - **Done - The criteria to consider when evaluating the platforms should include what languages are supported? can it be embedded easily? is it well known?**
* [x] evaluate options against this - **Done - After carefully evaluating the options I came up with, I found the best platform to use for our use-case is [Repl.it](replt.it). Based on the following, it is the only platform that ticks both requirements for what we need.**
<img width="642" alt="Screenshot 2020-03-10 at 1 32 05 PM" src="https://user-images.githubusercontent.com/17781315/76312601-b1de9f80-62d3-11ea-92bf-bbc20466bed7.png">

Bonus: write a short blog post about this

**Comment by lauragift21** [comment]
Update: I've read and watched the video and now working towards researching options for online code platforms. After doing a breadth-first search, I found a couple of platforms that will be useful for our use-case my next steps will be doing an in-depth look at each of the platforms and comparing each one based on what we need it for (ability to have live code examples in diff languages). [Here's my scratchpad for collecting info on this issue](https://hackmd.io/Z9AcvLCrT1W__ISoI2NshA?both) cc @rufuspollock

**Comment by lauragift21** [comment]
_**Identify Criteria Complete. A couple of questions to ask when evaluating options for which platform we should choose.**_

- What languages does the platform support?
- Can it be added as an embed to FD Docs?
- Is it popularly known or used?

**Comment by lauragift21** [comment]
_**Evaluate options against this**_ - After evaluating Repl.it comes back as the recommended option for us to use in our guide.

**Comment by lauragift21** [comment]
DONE. Completed research and analysis on a tool to use for embedding live examples on the guide. More details here: https://hackmd.io/Z9AcvLCrT1W__ISoI2NshA?both
