### ISSUE TITLE
[v2] Proof reviewing of content in v2 site

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#435]
We want to proof edit all key content pages and esp blog pages to ... 

* Make sure no TODOs or obviously missing content
* Tidy up metadata on blog, maybe add tags and new metadata

## Acceptance

* [x] Blog looks tidy
* [x] Pages are acceptable (no glaring TODOs or formatting errors etc)

## Tasks

* [x] Read contributing guidelines that explain about frontmatter etc https://github.com/frictionlessdata/website-v2/blob/master/contributing.md

Blogs - Review all blog pages - quite a few that need a bit of love.

* [x]  Basic proofing. Here are a few random examples of issues - probably more - **See list below. All DONE!**
* [x] Add tags in a systematic way - we can then have dedicated tag pages e.g. /tag/.../
  * [x] e.g. you could get field guide section or a tool fund grantees section this way
* [x] Add authors in systematic way (Everything is published by "Frictionless Data") - let's have all blog posts with authors **FUTURE**
* [x] many blogs have no description text in the blog index listing => we have to explicitly add this as per contributing guidelines **FUTURE**
* [x] show tags on blog index page if any provided in the frontmatter of the blog posts @monikappv 
* [x] On blog listing page the image often has odd drop shadow etc => remove @monikappv
* [x] All the posts about people are weird with just their name as title - we need some kind of title change e.g. "Contributor Profile: XXX", "Tool Fund Grantee: YYY" @vara
* [x] Old docs pages like publish-faq really need a bit of work to rename e.g. "FAQ on Publishing Data Packages" or similar
* [x] This page doesn't exist: http://next.frictionlessdata.io/products/data-package/ (from Tooling --> Data Package Tools')

### General content

* [x] Review all general content pages esp the tools pages to remove TODOs, fix grammar, links etc
* [x] Change "products" to tools

#### 1. Homepage

- [x] the description paragraph uses text we agreed to change from the branding doc - 'grace' should be 'gracefulness'
  - ✅ gracefulness is so ungraceful :wink: I agree we went for gracefulness in branding doc but for public comms. Won't die in a ditch on this one - happy to change now and check with Jo later. 
- [x] change terabytes to gigabytes
  - TODO: follow up the performance issue in goodtables

#### 2. On http://next.frictionlessdata.io/data-package/#datapackage-json:

```
Here is a much more extensive example of a datapackage JSON file:

!! Note: a complete list of potential attributes and their meaning can be found in the full Data Package spec.

!!! Note: the Data Package format is extensible: publishers may add their own additional metadata as well as constraints on the format and type of data by adding their own attributes to the datapackage.json.
```

- [x] Remove the exclamation points? Also, the first sentence says there will be an example, but then there isn't one.

### Blog

- [x] remove ! [dp clj](https://next.frictionlessdata.io/blog/2018/05/07/using-data-packages-in-clojure)
- [x] remove ! [dp java](https://next.frictionlessdata.io/blog/2018/04/28/using-data-packages-in-java)
- [x] fix table, remove !, also maybe rename because it is similar to next blog [GDP](https://next.frictionlessdata.io/blog/2018/04/06/joining-data-in-python/)
- [x] remove ! [joining python](https://next.frictionlessdata.io/blog/2018/04/05/joining-tabular-data-in-python)
- [x] remove ! [pub workflow](https://next.frictionlessdata.io/blog/2018/03/12/data-publication-workflow-example)
- [x] remove ! [well packaged](https://next.frictionlessdata.io/blog/2018/03/07/well-packaged-datasets)
- [x] remove ! [dp go](https://next.frictionlessdata.io/blog/2018/02/16/using-data-packages-in-go)
- [x] remove ! [dp r](https://next.frictionlessdata.io/blog/2018/02/14/using-data-packages-in-r/)
- [x] remove ! [dm4t pilot](https://next.frictionlessdata.io/blog/2017/12/19/dm4t)
- [x] there's some weird spacing happening [retina pilot](https://next.frictionlessdata.io/blog/2017/08/15/university-of-cambridge)
- [x] weird spacing too [cmso](https://next.frictionlessdata.io/blog/2017/05/23/cmso/)
- [x] data.world urls aren't rendering [dataworld](https://next.frictionlessdata.io/blog/2017/04/11/dataworld/)
- [x] remove ! [dataship](https://next.frictionlessdata.io/blog/2016/11/15/dataship/)
- [x] remove ! [open power](https://next.frictionlessdata.io/blog/2016/11/15/open-power-system-data/)
- [x] urls not rendering correctly [dp python](https://next.frictionlessdata.io/blog/2016/08/29/using-data-packages-in-python)
- [x] lots of rendering issues & tone is not friendly [publish online](https://next.frictionlessdata.io/blog/2016/08/29/publish-online)
- [x] fix table [python creating tab dp](https://next.frictionlessdata.io/blog/2016/07/21/creating-tabular-data-packages-in-python)
- [x] Need to add bco-dmo blog & catalyst blog @WFZjySnkTpSHZxoONQ7cZg can you explain this part to me?

### Tag themes

**Note - some tags already exist (like 'goodtables'), and show on the site, but aren't currently functional** -- later.

- Tool Fund
- Reproducible Research
- Demo
- Tutorial (or how-to?)
- DataPackage
- GoodTables
- Tableschema
- Publishing data
- Validating data
- Python
- JavaScript
- R 
- other languages?
- Pilot collaboration
- Case study
- Community
- Metadata
- Specifications

**Comment by rufuspollock** [comment]
@lwinfree following chat yesterday i've split this task out (from #428) and assigned to you. When do you reckon you could have this done by 😄 ?

**Comment by lwinfree** [comment]
@rufuspollock Great! I'll put it on my todos & try to finish by end of next week. I'm assuming it will take a while though to get thru all the content, so that might be optimistic. I'll use the checkmarks above to denote my progress.

**Comment by rufuspollock** [comment]
@lwinfree let me know when you have read the contributing guidelines in case you have any questions.

**Comment by lwinfree** [comment]
I'm going to go page by page and make notes in separate comments as I go. Also I want to preface these comments by saying that this site work is already a big improvement, and these comments are here to be helpful (and not nit-picky 😄)

**homepage**:
- the scrolling text is unpleasant from a UI perspective. I recommend removing the responsive typing.
- "zen" doesn't make sense here to me. I recommend removing
- the description paragraph uses text we agreed to change from the branding doc - 'grace' should be 'gracefulness'
- also in the description paragraph, I don't like the mention of terabytes as it is fairly inaccurate. Our tooling currently has problems with very large data. I recommend removing 'with terabytes'
- 'Start with _just_ what you need, scale as you grow.': change '_just_' to '_only_'
- we should review the adopted & used by section as I'm pretty sure some of them don't use FD anymore
- 'Especially diverse data _and/or_ across tools or teams': remove '_and_/'
- the whole 'Data Integration and Management' section is confusing to me - what is it's value add? how does it relate to FD? I recommend either removing this section or making it very clear how it relates to FD. If this section is kept, I would make it much shorter.
- Organization of the homepage - I think it would be nice to have the sections ordered like this: banner content, Some of our tooling, For anyone who works with data, Widely adopted & used, Why frictionless data (this way users understand what the product is & who it is for when they first look at the site)

**Comment by lwinfree** [comment]
On http://next.frictionlessdata.io/data-package/#datapackage-json:

```Here is a much more extensive example of a datapackage JSON file:

!! Note: a complete list of potential attributes and their meaning can be found in the full Data Package spec.

!!! Note: the Data Package format is extensible: publishers may add their own additional metadata as well as constraints on the format and type of data by adding their own attributes to the datapackage.json.
```

Remove the exclamation points? Also, the first sentence says there will be an example, but then there isn't one.

At the bottom, there is a link to the Data Package Viewer. This isn't maintained is it?

**Comment by lwinfree** [comment]
this page doesn't exist: http://next.frictionlessdata.io/products/data-package/ (from Tooling --> Data Package Tools')

**Comment by lwinfree** [comment]
For the 'Tooling' sections, I like the flow/layout of the [Goodtables page](http://next.frictionlessdata.io/products/goodtables/) much better than that of the [Table Schema tools page](http://next.frictionlessdata.io/products/table-schema-tools/)

**Comment by lwinfree** [comment]
Also for the Tooling sections, what happened to the idea of having the hexagons with different stages of the data workflow being shown on the pages? I thought that was a great idea!

**Comment by lwinfree** [comment]
For the [labs](http://next.frictionlessdata.io/products/labs), it would be nice to include a sentence asking for contributors & a link to contributor guide.

Also, I think we should include more things that were in the universe section of the old site, like https://github.com/nimblelearn/datapackage-m & the 2019 tool fund repos

**Comment by lwinfree** [comment]
In the Help section, for the 'Free Community Support' section, please add:

'Ask in the Chat room or open an issue in the GitHub Forum _and a member of the community or of the core team will gladly help you_'

**Comment by lwinfree** [comment]
In the [contribute page](http://next.frictionlessdata.io/contribute) we should link to a contributor's guide - but this guide doesn't exist yet 😞 This is what we usually link to https://github.com/okfn/coding-standards but we should make a real contributors guide.

**Comment by rufuspollock** [comment]
@lwinfree this is great 👏 One point that may be useful is to focus on the blog section (as per the tasks section) more than the whole site for now and then come back to main pages. E.g. we know there are some broken links and we'll collect those in one go. 

Also re the comments: would it be ok if you collect these in one list either in hackmd or into a separate section of the issue description as checklist items. That is much easier to then review and implement. If you do that it would be useful to separate bugfixes from general comments or improvements e.g. the contributing guide.

PS: when do you think you'll complete this?

**Comment by lwinfree** [comment]
Hey @rufuspollock sure I can compile these into a hackmd & I'll link it in the top comment so it can be more easily parsed.
The blog bits are on my to-do list this week, once I finish with the general proof reading. As there are a lot of blogs, I imagine this will take a while, but I'll try & update this with my progress as I go along.

**Comment by lwinfree** [comment]
@rufuspollock here's a doc listing changes for the blog: https://hackmd.io/8mNIPKnAQDKf21n47k-2Kg
My proposed plan is that I can spend some time next week making the changes (things like removing '!!!' and fixing formatting/typos). Let's discuss at our meeting on Tuesday?

**Comment by lwinfree** [comment]
@rufuspollock & team, here is a hackmd that has the above website edits collated: https://hackmd.io/l5GKi8tRRsqdbeiunDOJPA

**Comment by rufuspollock** [comment]
@lauragift21 can you check this out.

@lwinfree feel free to start making pull requests esp for the proof edit type stuff.

**Comment by lauragift21** [comment]
@rufuspollock @lwinfree I can also work on some of the edits requested.

**Comment by lauragift21** [comment]
@rufuspollock @lwinfree I've added the changes we discussed yesterday it's[ now live](https://next.frictionless.io).

@lwinfree can you clarify this line in changes for the blog. **_Need to add bco-dmo blog & catalyst blog_**

**Comment by lwinfree** [comment]
Thanks @lauragift21 that's great!
Yes, there are 2 blogs that I would like to add to the website. They are both from FD Pilot projects, and were originally published on the OKF blog, but I think really belong on the FD site. Could you please add them?
- https://blog.okfn.org/2020/02/10/frictionless-data-pipelines-for-ocean-science/
- https://blog.okfn.org/2020/03/18/frictionless-public-utility-data-a-pilot-study/
Let me know if you need anything, and thanks!

**Comment by lauragift21** [comment]
Yeah, sure I'll add those as well. @lwinfree

**Comment by lwinfree** [comment]
Hi all! I'm putting this thought here (but please move it/start a new issue if this isn't a good place):

To do: incorporate the hexes (see pic)
<img width="684" alt="data hexes" src="https://user-images.githubusercontent.com/17657625/79582419-58674e80-8091-11ea-944e-5d7168d639b3.png">

**Comment by rufuspollock** [comment]
FIXED. Everything done here. (done a few weeks ago).

/cc @lauragift21 feel free to start closing issues if you complete them  (you don't always need a review and if you do make sure to tag someone - probably not me! - to do it for you 😄
