### ISSUE TITLE
Content Writing for Frictionless Data Guide

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#440]
# Overview

Work out content for the guide on [next.frictionless.io](next.frictionless.io)
## Tasks
Write out content for the sections outlined below:
- [x] Table Schema
  -  [x] Table
  - [x] Table Schema
  - [x] Validation
  - [x] Tabulator
-  [ ] Data Resource
   -  [x] CSV Dialect
   -  [x] (Pre)view
   -  [ ] CSV to Excel (with Correct types)
-  [ ] Data Package
   -  [ ] Load to SQLite
   - [ ] Table References and Foreign Keys
   - [ ] Load to Postgres
   - [ ] Publishing Data(sets) 
- [ ] Flows
   - [ ] Flow Concept

---
 [Here's the FD draft content](https://hackmd.io/605lAS1xTHC0anrKhTXp5A?both)

See #430 for more context.

**Comment by lauragift21** [comment]
I'm currently working on [Validation](https://hackmd.io/605lAS1xTHC0anrKhTXp5A?both#Validation) section of the Guide.

### Task
- Write out content on validating table data
- Show examples using Goodtables Python and JavaScript Libraries.

### Blockers:

- Running examples with the JavaScript library. From the documentation I need to pass an `API TOKEN`, `API Source ID` as seen below.

```js
const source = 'helloworld.csv'
const options = {
  apiUrl: 'https://goodtables.io/api',
  apiToken: '<API_TOKEN>',
  apiSourceId: '<API_SOURCE_ID>',
}
const report = await goodtables.validate(source, options)
```
I'm blocked because I don't know where to get these values from running the example. cc @rufuspollock 

Even when I run the code block without passing the values I get this error because apparently those values are required.

 `Error: Options "apiToken" and "apiSourceId" are required`

**Comment by lauragift21** [comment]
@julietezekwe here's the issue I mentioned you can take a look at the repo to figure out the problem. https://github.com/frictionlessdata/goodtables-js

**Comment by julietezekwe** [comment]
Ok, I will take a look at it and revert

**Comment by lauragift21** [comment]
This is a duplicate of #430. so I'm closing to avoid confusion.
