### ISSUE TITLE
Guide: Table and Table Schema, Validation, and Tabulator

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#441]
Create the first main section of the guide on tables.

Subissue of: #430 

## Acceptance

- [x] We have a working guide for Table and Table Schema
- [x] We have a working guide for Validation and Tabulator

https://hackmd.io/605lAS1xTHC0anrKhTXp5A

## Tasks

* [x] What is a table
* [x] Table schema
* [x] Validation
* [x] Tabulator

**Comment by lauragift21** [comment]
In Progress: Content Draft written here. https://hackmd.io/605lAS1xTHC0anrKhTXp5A

**Comment by rufuspollock** [comment]
@lauragift21  let me know when you need this reviewed?

**Comment by lauragift21** [comment]
Alright, sure I will.

**Comment by lauragift21** [comment]
Update: Currently facing an Issue with the goodtables-js library I've created an issue on the repo to address it. https://github.com/frictionlessdata/goodtables-js/issues/23

**Comment by lauragift21** [comment]
Ready for review. The only blocker right now is adding a demo for goodtables-js library. @rufuspollock

**Comment by lauragift21** [comment]
The content is ready for review @rufuspollock

**Comment by rufuspollock** [comment]
@lauragift21 on my queue - could you get an initial review e.g. from @monikappv or @mpolidori?

**Comment by mpolidori** [comment]
@lauragift21 I can take a look ~later today~ this weekend

**Comment by mpolidori** [comment]
@lauragift21 Here's my [review HackMD](https://hackmd.io/7BRdmxuUT7y4gvxgmRvWEA?view) and a [diff](http://www.mergely.com/DecBQDT2/) (if you want to see the exact changes).

**Comment by lauragift21** [comment]
Thanks, @mpolidori. Really helpful review.
