### ISSUE TITLE
April 2020 Virtual Community Hangout

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#442]
Organize a 1h community hangout to chat about recent developments in Frictionless and data generally and next steps. Invite community members to it ...

Organizer: @lauragift21 (Datopian) and (tbc) @lwinfree 

Date: 20th April 5pm CET 

## Acceptance

* [x] Blog post for the hangout (where we can also post updates afterwards)
* [x] Announce on social media, x-post on blog.okfn.org and datopian.com and datahub.io (?)
* [x] An awesome 🎉 1h community hangout with at least 15 participants

## Tasks

* [x] Landing page / blog post
* [x] Zoom call link
* [x] Announce on social media

### People to invite

* [ ] @loleg 
* [ ] @Stephen-Gates 
* [ ] @johanricher
* [ ] @augusto-herrmann 
* [ ] @danielfireman 
* [ ] @Irio 
* [ ] @rufuspollock 
* [ ] @iSnow 
* [ ] @stephanmax 
* [ ] @andrejjh 
* [ ] @switzersc 
* [ ] @kleanthisk10 
* [ ] @monsauce
* [ ] @lilyzzhao
* [ ] @ousodaniel
* [ ] @seleneyang
* [ ] @roll 
* [ ] @amercader 
* [ ] @jobarratt 
* [ ] @chris
* [ ] @akariv 
* [ ] @georgeslabreche 
* [ ] @cblop
* [ ] @OriHoch 
* [ ] @pwalsh 
* [ ] @chris48s

**Comment by lwinfree** [comment]
awesome! I added more people to the list :-)

**Comment by augusto-herrmann** [comment]
Cool! I'm up for it.

**Comment by danielfireman** [comment]
> Cool! I'm up for it.

Same here.

**Comment by iSnow** [comment]
Depends on the COVID-situation. We have to work, home-school kids and look after relatives, so only if the pandemic situation is getting better.

**Comment by lauragift21** [comment]
Hi, A few updates here. We fixed a date for the hangout and I'm happy to invite you to join us for our first virtual hangout on 20th April. 5 PM (CET)  This is a great opportunity to know what's been going on in the Frictionless Data community. Can't wait to see you there. :slight_smile: 
https://frictionlessdata.io/blog/2020/04/16/annoucing-frictionless-data-virtual-hangout/

**Link to register:**
https://zoom.us/meeting/register/tJEqdOyspzgvG9wlVM_3Z_6yyL8wzc-v03Bq

**Comment by augusto-herrmann** [comment]
Speaking of Covid-19, we're [using Data Pacakges](https://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fturicas%2Fcovid19-br) for [tracking daily numbers](https://github.com/turicas/covid19-br/) by city in Brazil. Here's [a visualization](https://endoedgar.github.io/covid19-monitorbr/#/BR/SELECT_CITY/last) using that data.

**Comment by rufuspollock** [comment]
@augusto-herrmann cool! We're doing quite a bit here https://github.com/datasets/covid-19 + https://datahub.io/core/covid-19 and https://datahub.io/collections plus there is a dashboard here: 
all running off data packages:

https://datopian.github.io/covid-19/

![image](https://user-images.githubusercontent.com/180658/79576780-19062580-80c4-11ea-83d0-bfcd44e4b3a7.png)

**Comment by rufuspollock** [comment]
FIXED. Hangout happened yesterday and was great. Follow up in #477.
