### ISSUE TITLE
Gift intros herself e.g. on chat and in a blog post

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#443]
When I am am member of FD community or checking out website i want to know if new people are contributing and who they are so that I know what is going on and that things are progressing

## Acceptance

* [x] Post is up - https://www.datopian.com/blog/2020/03/20/joining-the-frictionless-data-team/
* [x] Have said hello (maybe more than once) on chat ...

## Tasks

* [x] Write a short blog post introducing yourself and you work at Datopian (frictionlessdata.io)
* [x] Short hello on chat

**Comment by lauragift21** [comment]
I wrote up a blogpost @rufuspollock can you take a look and let me know if it looks good and also share where this should be published. Datopian blog or FD? https://hackmd.io/HluqIwd-SUmFs5lmGziqzA

**Comment by lauragift21** [comment]
Also is it okay to post this to my personal blog and dev.to?

**Comment by rufuspollock** [comment]
@lauragift21 looks great and i've made a few tweaks (you can check the diff to see).

Re x-posting: absolutely yes 👍 👍

**Comment by lauragift21** [comment]
Alright, thanks @rufuspollock  Lastly, should this go on the Datopian.com blog?

**Comment by rufuspollock** [comment]
@lauragift21 did you post on chat? did you get any responses?

**Comment by lauragift21** [comment]
Yes, I posted on chat and the forum. No response.
