### ISSUE TITLE
Guide: Data Resource, CSV Dialect (CSV to Excel..)

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#444]
Write out the section for the guide on Data Resource.

subissue of: #430 

### Content Draft

https://hackmd.io/tEXrveiyRN2OfxrnwPZ_7g

## Acceptance

* [x] we have a working guide for Data Resource, CSV Dialect
* [ ] we have a working guide for (Pre)view and CSV to Excel (with Correct types)

## Tasks

* [x]  Data Resource
   * [x] Tabular Data Resource
* [x]  CSV Dialect
* [ ]  (Pre)view - i.e. viewing the data resource (on terminal, or in markdown or into html or even live so you can edit as you go). See `data info` and `data cat` functionality in https://github.com/datopian/data-cli (an animation of this would be nice).
  * [x] Terminal
  * [ ] Code
  * [ ] Live reload (??)
  * [ ] Convert to html
* [ ]   CSV to Excel (with Correct types)

**Comment by lwinfree** [comment]
Hi @lauragift21! I just read through the current guide content & it looks really nice! I'm wondering if you have a plan to incorporate the data package information into the guide as well? I think it should be included. Thanks for your work here!

**Comment by lauragift21** [comment]
Thank you @lwinfree! Yes, one of the sections I'm working on is focused on Data Packages.

**Comment by lwinfree** [comment]
Great! Thanks - I think it is really coming together :-)

**Comment by rufuspollock** [comment]
@lauragift21 can you make an all out effort to get *something* shipped by next Tuesday (19th).

**Comment by lauragift21** [comment]
Yes I will @rufuspollock

**Comment by lwinfree** [comment]
closing as this has been incorporated in the main site & framework docs
