### ISSUE TITLE
[v2] Update to new (final) FD logo (v3)

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#445]
*Description*

Issues

* Navbar logo is in PNG format [and should be in svg format] - can have backup png if needed (e.g. svg does not always copy and paste well)
* Logo is actually not correct in the sense that the "flow" in the middle actually extends outside the circle and turns into a hockey stick (left over from previous design efforts)
  * does not end cleanly at edge of circle

## Acceptance

* [x] SVG logos used by default (can keep png if necessary as useful backup)
  * [x] These are named well and sensibly e.g. `frictionless-logo.svg`, (same as previous - is it needed?) `frictionless-color-logo.svg`, `frictionless-black-logo.svg``frictionless-color-fuul-logo.svg`, `frictionless-black-full-logo.svg`
* [x] We the logo correctly and perfectly done in color and greyscale
* [x] (optional) frictionlessdata.io/design exists with these listed like on zeit
* [x] logo looks ok in every section e.g. footer, navbar (currently the logo in the footer has a white line flowing outside of the circle)  

## Tasks

* [x] Navbar logo is in PNG format. We have the logo in both SVG and PNG formats. However, the `frictionless data` text next to the circle is rendered differently in both versions and the PNG version looks much better on the navbar  => we need to align the SVG version with the PNG one.
* [x] ~~ask Sylvie to edit it~~ change of plan 
* [x] get the xd file
* [x] edit
* [x] implement
* [x] add a design page containing our different logo versions (like zeit.co)

## Analysis

PNG version :+1:  ![logoNavbarPNG](https://user-images.githubusercontent.com/56799741/77437325-31e52900-6ded-11ea-9384-f4e98c78e5ac.png)

SVG version :-1: 

![logoSVGfd](https://user-images.githubusercontent.com/56799741/77437284-242fa380-6ded-11ea-8e17-10f616ff2752.png)

### Logo on colored backgrounds

The logo looks great on white background, see below:

![logoCircleFD](https://user-images.githubusercontent.com/56799741/77435802-6657e580-6deb-11ea-890e-7b7a8189f117.png)

but it looks weird on colored backgrounds due to the fact that the white line is flowing outside of the circle, see below --> the flowing line should stay within the circle.

![logoGrayBGfd](https://user-images.githubusercontent.com/56799741/77435825-6fe14d80-6deb-11ea-9131-3ce61854e0f0.png)

**Comment by lauragift21** [comment]
@monikappv are you already working on this?

**Comment by monikappv** [comment]
@lauragift21 received the xd file today, I'm on it.

**Comment by monikappv** [comment]
Logos are correctly done and in SVG format live on https://next.frictionlessdata.io/.

Created a design page, see screenshots below or live on https://next.frictionlessdata.io/design

![designpageFD](https://user-images.githubusercontent.com/56799741/77808986-63345200-7096-11ea-870f-fcf31b61cdca.png)

![designpage2FD](https://user-images.githubusercontent.com/56799741/77808987-63cce880-7096-11ea-8b22-939d259043a0.png)

**Comment by monikappv** [comment]
FIXED.
