### ISSUE TITLE
Website v2.1 - misc fixes after release of v2

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#446]
v2 is shipped ... (https://github.com/frictionlessdata/project/projects/2) and there's more to do 😄 

## Acceptance

The blog has pagination implemented

## Tasks
* [x] Chat link in the navbar
* [x] *Nice* Github repo link in the navbar (just the icon please!) - should link to the base I think or the project repo ... **Gift - Not able to add icon because of how vuepress config works**
* [x] get rid of cypress for now ...
* [x]  many blogs have no description text in the blog index listing => we have to explicitly add this as per contributing guidelines
* [x] Set the meta / social tags in HTML header from key frontmatter variables so that when you paste a link somewhere e.g. twitter, Facebook, chat it comes with nice info. **This is already set as default but I went ahead to add an image to the preview generated for twitter, Facebook, etc**
* [x] Comments on blog - https://vssue.js.org/
*  [x] some publication dates are incorrect? **probably! were taken off Github commits** **after go-live**
* [x] why is TeamProfile in components rather than theme/components?  @monika 
  * NB: moved to theme/components for testing purposes and it stopped working - will leave in components for now and will investigate the reason later. - **@gift Investigated this and it seems any Vue component used within markdown should always be stored in `components/` if moved to `themes/component/` it won't work properly.**
* [x] Enable click event on mobile for nav items
* [x] Pagination on the blog - It would be nice to have page numbers/how many results at the bottom of the blog page where it says next & previous (like page 1/4 or something).
* [x] Steps / Jobs to be done are back ... **big 🐘**
* [ ] authors are all incorrect **I'm not sure where to find correct authors of some post tagged Frictionless Data**
* [ ] Gravatar images on posts with their authors ... (would require a mapping file of authors to their emails) - **clarification needed on the implementation of this.**

**Comment by lauragift21** [comment]
DONE. Moving the last undone item to the next sprint.
