### ISSUE TITLE
[v2] Add functionality to tags on FD blog page

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#447]
Issue: some blog posts have tags, but the tags do not have any functionality (nothing happens when you click on them).

## Acceptance

* [x] we have a tags page that contains blog post links grouped by their tags 
* [x] all tags lead to particular relevant section on the tags page when clicked on them

## Tasks

* [x] add tags.md page
* [x] investigate the problem with the tags not working
  * [x] no tags page
  * [x] no path of tags defined
* [x] solve it

**Comment by monikappv** [comment]
FIXED. 

See live on https://next.frictionlessdata.io/blog/.
