### ISSUE TITLE
Fix redirect bug on website 

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#448]
When you are redirected to frictionlessdata.io you have to reload the page to see the result else it'll lead to a 404 page.

## Acceptance Criteria
- [x] Redirection is working as expected without the need to reload the page.

## Tasks
- [x] Reproduce the bug with `frictionlessdata.io/field-guide` 
- [x] fix the redirect bug
Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by lauragift21** [comment]
My understanding is this behavior is from vuepress and redirecting after build/production will result in a 404 page but works after a refresh. See https://github.com/vuejs/vuepress/issues/160

I've not found a solution to this yet and will need help if anyone is open to looking into this together. cc @lwinfree

**Comment by lauragift21** [comment]
I've fixed this now. I found a helpful solution to diverting the behavior. It's an issue with server-side mismatch issue and vuepress. More details on that here https://github.com/vuejs/vuepress/issues/1382

This https://frictionlessdata.io/field-guide now  redirects to https://frictionlessdata.io/guide

@lwinfree @rufuspollock

**Comment by lwinfree** [comment]
Awesome @lauragift21 !
