### ISSUE TITLE
[v2] Have footer content only in one file

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#449]
Currently we have the footer content duplicated across two files..

## Acceptance

* [x] regardless of how many footers we use, we have the footer content only in one file --> in the config.js file

## Tasks

* [x] set variables for the footer content in the config.js 
* [x] replace the content of the two footers with variables e.g. {{ $site.themeConfig.footer_col1_title }}

**Comment by monikappv** [comment]
FIXED. 

Created a PR - https://github.com/frictionlessdata/website-v2/pull/61.
