### ISSUE TITLE
[docs] HowTos Template

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#451]
For creating howtos we want a template that we can use.

We also want to decide e.g. if we are using jupyter notebooks and if so where we are storing the source etc.

## Acceptance

* [x] Howtos template
* [x] Use (or not) of things like jupyter notebooks
* [x] How we storing (version controlling) these notebooks
* [x] How we are embedding / integrating these notebooks

## Tasks

...

**Comment by lwinfree** [comment]
Template in colab notebook is here: https://colab.research.google.com/drive/1zws0ZRz37z4QN5eez1TNdoU45crvPSke

The plan is that Lilly will write the how-to's in colab, then convert to markdown to give to Gift

**Comment by rufuspollock** [comment]
@lwinfree great 👍 

Any thoughts on how we version control? If we store these notebooks in git(hub) we get that for free i guess (and can embed more easily)? (is there a way to auto import to colab from git(hub)?)

/cc @lauragift21

**Comment by lwinfree** [comment]
@rufuspollock Yeah, I think we should store them in GitHub, and yes we can automatically add them to GitHub via colab's innate menu functions - so that's nice! I think the next question is which repo we store them in.

**Comment by lauragift21** [comment]
Hi @lwinfree. Any plan on this I think we can store them on a different repo or subfolder in website repo. Let me know what you think.

Also, did you figure out the best way to embed the code examples?

**Comment by lwinfree** [comment]
Hi @lauragift21! I like either of those options, and would lean toward having all the notebooks in a separate repo. WDYT?

**Comment by lauragift21** [comment]
Yeah, a different repo works too. 

I'm thinking of how we want it displayed on the website.  See this example(https://vuejs.org/v2/examples/) are we able the embed directly on the website.

**Comment by lwinfree** [comment]
Oh yeah, I think that could work! If we can't get it embeded totally, we could have the code in a markdown chunk with a link to run it in its notebook in the repo, which wouldn't be as nice as embeded, runnable code, but it would work.

**Comment by lauragift21** [comment]
Alright. Let's see how that works in the meantime we can have another possible option that allows embedding (i.e repl.it).

**Comment by rufuspollock** [comment]
FIXED. See template  in https://colab.research.google.com/drive/1zws0ZRz37z4QN5eez1TNdoU45crvPSke
