### ISSUE TITLE
Add Case Studies Tag Systematically to the Blog

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#452]
When looking at Frictionless Data I want to know who has used this and how so that I can see if it fits my needs => Case Studies

## Tasks

- [x] Tag the case studies in the blog /tags/case-studies/ which listed them all …
- [x] https://frictionlessdata.io/tags.html - Remove the ‘html’ from the url
- [x] Can we get a page per tag …
- [x] Add “Case Studies” to the navbar
- [x]  Add tag themes to blogpost without tags

**Comment by lauragift21** [comment]
## tag themes:
**Note - some tags already exist (like 'goodtables'), and show on the site, but aren't currently functional**
- Tool Fund
- Reproducible Research
- Demo
- Tutorial (or how-to?)
- DataPackage
- GoodTables
- Tableschema
- Publishing data
- Validating data
- Python
- JavaScript
- R 
- other languages?
- Pilot collaboration
- Case study
- Community
- Metadata
- Specifications
