### ISSUE TITLE
[howto] Write 2-3 howtos

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#453]
Write the first howtos and have them live on the website at e.g. `/howto/.../`

## Acceptance

* [ ] 1-3 howtos published on the site

## Tasks

* [x] Identify the top  2-3 howtos we want to write
* [x] Write one of them
* [x] Review
* [ ] Publish
* [ ] Rinse and repeat

**Comment by rufuspollock** [comment]
@lwinfree has done one and will do remaining two in next sprint (by 5 may).

**Comment by lwinfree** [comment]
I'll ask @roll to review the completed how-to's as well

**Comment by lauragift21** [comment]
Hey @lwinfree. Any update on this do you want me to help review already written Howtos?

**Comment by lwinfree** [comment]
Hi @lauragift21! Sure, if you have time. Otherwise I will ask Evgeny to review them. They are marked as "ready for review" in column G: https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1272791416 Thanks!

**Comment by roll** [comment]
@lwinfree the 2 I saw look good to me

**Comment by lwinfree** [comment]
Hi @roll have you had time to look into posting these on the website?

**Comment by roll** [comment]
We can merge this issue with a high-level https://github.com/frictionlessdata/project/issues/542 as we're going to add a lot of documents like "Working with SQL in Frictionless" etc

**Comment by lwinfree** [comment]
closing this as it was part of #542
