### ISSUE TITLE
Announce (blog etc) about new frictionless data website

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#454]
Announce (blog etc) about new frictionless data website and post it around in different channels (e.g. datopian blog; twitter; gitter; fd blog; data community…) 

## Acceptance Criteria
https://frictionlessdata.io/blog/2020/05/01/announcing-new-website/
- [x] A blog post announcing the release is published
- [x] Shared blog post on Twitter
- [x] Shared blog post on Discord
- [x] Shared blog post on Gitter

## Tasks

- [x] Write a blog post announcing the recent changes to the website
- [x] Share on different platforms (Will have to get final go from both Rufus and OKF team. If we are satisfied with the current state of the website.)
