### ISSUE TITLE
Rename website repo to website-old and website-v2 to website

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#455]
Minor "house-cleaning". Should be very straightforward.

## Acceptance

* [x] `website` repo is renamed to `website-old`
* [x] `website-v2` repo is renamed to `website`

## Tasks

* [x] check what repositories we have for the website --> `website`, `website-v2` and `new-website`
* [x] have a look at `new-website` repo and decide if we need it --> some old vuepress experiment --> `archived` for now, might as well delete it (?)
* [x] rename `website` repo to `website-old`
* [x] rename `website-v2` to `website`

**Comment by monikappv** [comment]
FIXED.
