### ISSUE TITLE
Improve the general look and feel of the FD home page

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#456]
Make the home page look more professional based on Sylvie's new moodboard https://drive.google.com/open?id=1vcBCijEa7uRTLbsqa_0eUDvu6qkyV6hz

A preview of the new moodboard:

![preview](https://user-images.githubusercontent.com/56799741/79446310-b1c67380-7fe6-11ea-8bdd-17021b7ae1f2.png) 

## Acceptance

* [ ] home page looks better than the current one
* [ ] home page looks more professional

## Tasks

* [x] brainstorm ideas for improvement
* [x] research; look for cool websites / sections for inspiration 
* [x] pair with @lauragift21 and @julietezekwe and improve the sections one by one
* [x] based on the mutual work / gathered materials / ideas, consolidate a mockup suggestion according to your own point of view --> the outcome would be three mockup versions 
* [x] ask for feedback
* [ ] update / improve accordingly to the received feedback
* [ ] implement

### v1 

@lauragift21 

![FDv1](https://user-images.githubusercontent.com/56799741/79374550-11c60700-7f60-11ea-87a6-06c463e2edfe.png)

### v2 

@julietezekwe 

![FDv2](https://user-images.githubusercontent.com/56799741/79374625-1f7b8c80-7f60-11ea-8219-f8509ff45a34.png)

### v3

@monikappv 

![FDv3](https://user-images.githubusercontent.com/56799741/79374675-2904f480-7f60-11ea-82b5-754e457c3b1e.jpg)

**Comment by monikappv** [comment]
@rufuspollock please review and let us know your thoughts 😄

**Comment by monikappv** [comment]
Also, @lwinfree @jobarratt your feedback, suggestions a/o ideas for improvement are very welcome.

**Comment by lwinfree** [comment]
Hi @monikappv! These look really nice overall! I like V1 the best. I still think that the "Some of our Tooling" section should go up higher. I would put it after "For anyone who works with data". Also, I'd change most of the wording in the progressive data toolkit paragraph. I can play with that & give you a suggestion in a later comment.

I'd be curious to hear people's opinions about the green? (Personally that is one of my favorite colors, so I'm kinda into it)

**Comment by monikappv** [comment]
@lwinfree thanks for the speedy feedback :clap:  

P.S. another thing that would be very helpful for us when it comes to content - if you could come up with some descriptions for the 3 listed things in the 'Data integration and management' section, that would be amazing! (right now there's just some random sentence there)

**Comment by jobarratt** [comment]
@monikappv thank you for sharing!  think these are a huge improvement. I think v2 is my favourite but honestly i would be pleased with any of them. 

it would be great if you could give us access to Sylvie's mood board. I'd be interested to see this. 

I like the green, i would not have imagined that i would... but i think it's subtle and classy. I think it works really well with the colour illustrations.

**Comment by roll** [comment]
I really like `v2` though the logo looks alien for this casual style

**Comment by monikappv** [comment]
@roll @jobarratt thank you both for your feedback! :sun_with_face:

@jobarratt I uploaded a preview of the moodboard (more like a consolidation of elements and styles) in the issue description.

**Comment by rufuspollock** [comment]
@monikappv I think these are generally great and a big improvement 👏 .  Overall i think v2 is my preference on coloring atm. Comments / questions

* what's the different between the 3 versions - just in the coloring (?) (i struggled to see the differences super well). (Generally for comparisons it would be useful to have fairly radical different options rather than say just changes in the outline of a box).
* Am i supposed to review copy changes? e.g. Is the copy change in the hero section intentional? What about the overall tagline?
  * I wouldn't do copy changes usually in these as that confuses things a bit
* Minor things like a video / play icon on "Why frictionless data"
* I'd have the toolbox in your primary color e.g. orange
* Coloring e.g. of people in v2 is excellent
* Lines aruond frictionless data is a very nice idea - it kind of links to the techy feel (it reminds me of illustrations of git commit trees etc) and was a bit like one logo option. I think we could use this more e.g. in working on the hero section - see future stuff below

Future ...  Things it would be nice to look at (in the future):

* hexagons rather than circles as our default framer (if we are going for that)
* indicating in hero section some of the tooling e.g. maybe you could have our symbolic tools linked to the box ...

**Comment by lwinfree** [comment]
+1 to Rufus' comments. Also, I will send some edits/ideas for text @monikappv but I also understand that copy editing this right not probably isn't the best time. Thanks all!

**Comment by lwinfree** [comment]
Hey y'all, another thing I just noticed is that all these options look identical to the new Datopian homepage design, so we should probably change the colors on one or the other (I'd be open to also changing some graphics, but I think at least changing the colors would be a good solution).
Also, this image was designed to go on FD (and my opinion is that it is really useful!) so I'd like to see it incorporated still: 
<img width="684" alt="datahexes" src="https://user-images.githubusercontent.com/17657625/79489915-aa509b80-7fe1-11ea-8294-6c509ada3437.png">

**Comment by rufuspollock** [comment]
@lwinfree can we get a separate issue for this - they seem somewhat separate points e.g. 

- systematically changing colors is a design system change
- the hexagon item has a separate issue i think (or if not it should do 😄) (and 👍 on us incorporating it - it just needs a bunch of work to do properly ... - though we could use the basic version quickly ...)

**Comment by jobarratt** [comment]
The effect of the Datopian site and Frictionless Data site having the same design means that Frictionless Data looks, to all intents and purposes, like a Datopian project. It doesn't reflect the collaborative nature of the project. 

For Frictionless Data we either need a brand that factors in both partners visual identity, or we have one which is entirely distinct. Throughout this rebrand process, and work on the website, i’ve assumed the latter and i think that was a fair assumption to make.

Agree that changing the colours is a design system change, and also feel that a design system change is what’s needed. As far as changes go it’s a fairly easy to implement and i feel the minimum we should do.

**Comment by lwinfree** [comment]
Hey Rufus I separated out my comments & the hex issue is part of this now (feel free to move it though if that is a bad spot - it was the best I could find) https://github.com/frictionlessdata/project/issues/435

**Comment by rufuspollock** [comment]
@jobarratt can we get a different issue for this unless this is specifically about *this* front page.

The overall look of the home page and Datopian home page are IMO pretty different. The main resemblance atm is the orange - which only arose out of the change of logo - the previous one was blue and we had a blue color schema. (and potentially some similar layout b/c both using vuepress and some parts of its default theme - just as if you used bootstrap - something i imagine that will change as we do more work ...)

> The effect of the Datopian site and Frictionless Data site having the same design means that Frictionless Data looks, to all intents and purposes, like a Datopian project. It doesn't reflect the collaborative nature of the project.

I note the main change which is the orange arose from redoing the logo ...

> For Frictionless Data we either need a brand that factors in both partners visual identity, or we have one which is entirely distinct. Throughout this rebrand process, and work on the website, i’ve assumed the latter and i think that was a fair assumption to make.

I don't think there is any requirement for FD to reflect *either* (or both) of the partners visual identity personally and there was certainly no intention or effort at our end to have it reflect datopian. see previous points.

> Agree that changing the colours is a design system change, and also feel that a design system change is what’s needed. As far as changes go it’s a fairly easy to implement and i feel the minimum we should do.

Great, as per comment to lilly please open a new issue for this specifically 😄  - i think it is a distinct question from the general layout of the home page ...

**Comment by rufuspollock** [comment]
> Hey Rufus I separated out my comments & the hex issue is part of this now (feel free to move it though if that is a bad spot - it was the best I could find) #435

I think it should be a new issue then - i don't think #435 is right place as that is done. I think best best is either https://github.com/frictionlessdata/project/issues/421 (closed) or a new issue.

**Comment by lwinfree** [comment]
Hey @rufuspollock , mine + Jo's comments are specifically about this homepage and these design mockups, so I think this is the best place for us to discuss this. I want to reiterate that I really like these homepage options that Monika posted and think they look good overall! The only issue that is stopping us from signing off/approving/being 100% on board is what Jo described. As I mentioned earlier, and which I think you are agreeing with, the colors are the same, so I think a (hopefully) quick solution here is to change the colors so they aren't the same. I don't have any say over the Datopian site, so I will obviously defer to you & your team for any changes there (and I don't want to get involved there either for the record). I also don't want to block the FD homepage release as I really do think it will look good & am excited for it to go live, but I strongly feel that the sites should not look so similar, so I am requesting changes.

**Comment by rufuspollock** [comment]
@lwinfree i feel there are 2 things here and i think we could keep them distinct so we can keep this thread reasonably clear and keep things moving.

1. the general design of this front page
2. changing colors (if necessary) b/c you and jo feel there is too much similarity to datopian.com and this may lead to issues/confusion for someone

I feel that we are all generally happy with the overall layout / design of the front page so I think (1) could proceed. On (2) let's open a *separate* issue and have the discussion then and then make changes as necessary be that to colors, fonts, logos etc.

I suggest this as I think it may take a bit of time to discuss changing the colors esp of the logo etc. So i'd prefer us to get moving with (1) so we have a nice front page and then address (2).

**Comment by lwinfree** [comment]
Hey @rufuspollock I get what you are saying, but the color is an integral part of the design of this homepage, so I think we need to resolve this. I don't see a benefit in opening a new issue to address a change in the Datopian site - I'd prefer to not be involved in that process as I don't think my opinion should matter for Datopian products :-)
To move forward here with this issue, I'd suggest that we agree that option #2 is the best (I think that is the most popular vote) but that we need a new color. How can we make that change? Maybe a light grey-blue instead of the green? Could Sylvie do a version like that?

**Comment by rufuspollock** [comment]
> I don't see a benefit in opening a new issue to address a change in the Datopian site - I'd prefer to not be involved in that process as I don't think my opinion should matter for Datopian products :-)

I was suggesting opening an issue about changing color scheme for *FD* @lwinfree - nothing to do with Datopian 😉 

@lwinfree sylvie isn't doing any more on this project as she is very busy with other things. I suggest you go through and come up with your alternate rendering - we can send you the draft in XD or your own favourite design program - and then we can compare on how it looks. Could you *please* do this asap as it would be nice to get this shipped and its the blocker for the announce 😄 

I'm still personally of the suggestion that we get the thing up so we can see and then make color tweaks which would give more time but if that's not an option then please make suggestions asap.

**Comment by lwinfree** [comment]
Hey! I don't have a design program :-( But that's why I suggested a light grey-blue in my above comment - I think that would look nice! What if we launch this version with a grey-blue and then we can iterate over it if it looks weird? I'm thinking like this hex code #cfe1e6
Again, I am on board with getting this decided ASAP so we can launch this nice new homepage design.

**Comment by rufuspollock** [comment]
@lwinfree you can download XD for free and play around. I think that is what the others did. I think it will be worth it as colors tend to affect each other (e..g you change one you need to change another etc - which was why earlier in this thread i flagged this is as a design system time that would prob merit a separate issue).

**Comment by lwinfree** [comment]
Hey @rufuspollock maybe the person on your team that made this (I assume it was Monika?) can join our meeting tomorrow and they can change the color while we watch & then we can decide & then be able to release tomorrow? Seems like the easiest/fastest solution to me!

**Comment by jobarratt** [comment]
good idea Lilly! Seems like a good and quick way to resolve this. But if this is impossible, Rufus please send me the InDesign files and i will look at or ask another designer to look at. 

The original issue raised is not with the colour. The issue is that the design of the new Datopian site looks too similar to this one.  It's not an agreed fact that the sites look pretty different, though its noted this is what you think. For me it's an issue. A change of colour was just a suggestion to mitigate this as it is an easy design element to change. There are other design elements that could, and i think should, ultimately change, and i think this is the right place to discuss this issue. I would say the issue is with the Datopian site rather than this one, but given we don't have a say about what happens there, and would not want to, i think this is the right place to discuss this. I just don't want the real issue obscured by creating another ticket about the colour.

**Comment by monikappv** [comment]
FIXED.

The new landing page is implemented and live on https://frictionlessdata.io/.
All people's improvement suggestions are stored in #484. If anyone has other comments / suggestions, please add them in the new issue. 

Here is a screenshot of the home page hero with the new color palette -->

![FDhero](https://user-images.githubusercontent.com/56799741/80096640-932a2480-8572-11ea-90f8-b7dfb0a2793c.png)
