### ISSUE TITLE
Follow up to April 2020 Community Hangout

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#477]
We have an *awesome* community hangout #442  🎉 and we should write up and post so that those who couldn't make it can find out and follow up
 
## Acceptance
https://frictionlessdata.io/blog/2020/04/28/recap-post-frictionless-data-hangout-april-2020/
* [x] Recording posted afterwards on youtube channel and embedded in a post (or follow up post)
* [x] New blog post (or update on old one with post info at the top)
  * [x] A few hightlights
  * [x] Key items
* [x] (?) Flag date of next one ... 

## Tasks
- [x] Upload recording to YouTube
- [x] Write a recap post with a few highlights from the event and announce a date for the next one.
