### ISSUE TITLE
Fix bug - logo appearing outside of the navbar

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#478]
when I run the site locally, the logo looks fine, but when I deployed it --> 

![logoBug](https://user-images.githubusercontent.com/56799741/79917388-16dcf780-8433-11ea-86df-0dba9e04330b.png)

## Acceptance

* [ ] logo is placed within the navbar on the live version

## Tasks

* [x] find a temporarily solution so that it looks ok
* [ ] identify the problem
* [ ] fix it..

**Comment by monikappv** [comment]
## Temporarily solution

added 
```
margin: -2.2rem;
padding-left: 2rem;
```
to the logo

**outcome:** 
![fdFIXED](https://user-images.githubusercontent.com/56799741/79925881-2a448e80-8444-11ea-9ef5-07fadb51149e.png)

however, it looks now wrong when ran locally --> 
![logoBugwtf](https://user-images.githubusercontent.com/56799741/79925962-5eb84a80-8444-11ea-9a15-f40253aa88d3.png)

--> I need to identify the reason for that bug and find a better solution.

**Comment by sglavoie** [comment]
**WONTFIX**: Closing because the issue has been resolved already. No more action needed: the logo currently looks fine.
