### ISSUE TITLE
Add forum link to discord in navbar

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#479]
When visiting f15a I want to chat with people (quickly) so that I can get help / meet the community

Maybe also add to footer with number of people online - see e.g. footer of https://apostrophecms.com

## Acceptance

* [x] Link in navbar that has good UX (people clear there is chat)

## Tasks

* [x] Get discord unlimited invite link
* [x] Add icon to navbar with link (or maybe just text "Chat") (want hover
* [x] (?) add to footer (with info on number online)

**Comment by lauragift21** [comment]
Great! I will replace where we have gitter linked to discord instead and probably make it a bit more easy to find on the navbar. @rufuspollock
