### ISSUE TITLE
Improve the FD home page based on people's feedback

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#484]
## Acceptance

* [ ] ..

## Tasks

* [x] gather feedback suggestions from #456
* [ ] create a plan on how / whether to implement
* [ ] implement

## Improvement Suggestions

* [ ] "Some of our Tooling" section should go up higher (after "For anyone who works with data")
* [ ] improve wording
* [ ] hexagons rather than circles as our default framer (if we are going for that)
* [ ] indicating in hero section some of the tooling e.g. maybe our symbolic tools linked to the box ...
* [ ] incorporate hexagon

**Comment by rufuspollock** [comment]
I also think "Some of Our Tooling" is now overly spaced - we can have these all on one line like b4

Also the orange separator / underline under "Some of Our Tooling" looks wrong

![image](https://user-images.githubusercontent.com/180658/82613157-e967a300-9bc4-11ea-9521-e7ea3cf22e5d.png)

**Comment by sglavoie** [comment]
**WONTFIX**: The section "Some of Our Tooling" is fixed (centered and on one line). Please feel free to re-open this issue if we are going to change the shape of the items in this section from circles to hexagons.
