### ISSUE TITLE
Guide: Data Package

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#487]
Write out the section for the guide on Data Package.

subissue of: #430 

### Content Draft

https://hackmd.io/TzC1nO_-STiu63D_OISOhA

## Acceptance

* [ ] we have a working guide for Data Package

## Tasks

- [ ] Load to SQLite
- [ ] Table References and Foreign Keys
- [ ] Load to Postgres
- [ ] Publishing Data(sets)

**Comment by sglavoie** [comment]
**WONTFIX**: Closing because the task list is not detailed enough and there is no sign of activity on this issue in the recent months. Please feel free to re-open with more details. Similar to #488.
