### ISSUE TITLE
[specs] Merge new site branch into master and backport changes from last few weeks

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#489]
An oversight has meant we never merged our development branch https://github.com/frictionlessdata/specs/tree/back-to-own-subsite-2020 back into master when we went live ...

This means that recent changes in master aren't showing up on the site ... 

Also it means things like "edit this page" are broken on site since they go to master.

## Acceptance

* [x] Master has live site and has both latest changes and https://github.com/frictionlessdata/specs/tree/back-to-own-subsite-2020
* [x] https://github.com/frictionlessdata/specs/tree/back-to-own-subsite-2020 no longer exists

## Tasks

* [x] Back port recent changes from master into https://github.com/frictionlessdata/specs/tree/back-to-own-subsite-2020
* [x] Then merge that back into master
* [x] Remove https://github.com/frictionlessdata/specs/tree/back-to-own-subsite-2020

**Comment by rufuspollock** [comment]
@monikappv could you look into this with @lauragift21 support.

**Comment by lauragift21** [comment]
@rufuspollock I can investigate this too.

**Comment by rufuspollock** [comment]
@lauragift21 can you delete the branch and then "close" this with FIXED comment. Also we need to check the site built ok!

**Comment by lauragift21** [comment]
FIXED. [PR Merged](https://github.com/frictionlessdata/specs/pull/673)

The website is up and running correctly.
