### ISSUE TITLE
[epic] Track Monthly Traffic Metrics

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#491]
We want to be able to track traffic on the website and see how we are doing overall.

## Acceptance

* [x] We have a way to track 
  * [x] FD website traffic metrics --> for now we use just Google Analytics
  * [x] FD repos metrics --> https://github.com/frictionlessdata/pm-metrics

## Tasks

* [x] Write a script that captures our key traffic numbers on FD on a monthly basis - script is here https://github.com/monikappv/frictionless-data-repos/blob/master/script/process.py
* [x] ~~Create a small dashboard / traffic report using data studio~~
  * [x] add graphs
  * [x] add important traffic numbers
* [x] data package the script
* [x] push to a separate repo called pm-metrics https://github.com/frictionlessdata/pm-metrics 
* [x] add instructions on how to use
* [x] apply to FD and push to the repo 
* [x] fix watchers number 
* [x] data package it 

**--> script and datapackage here https://github.com/frictionlessdata/pm-metrics**

was **blocked** a bit as i constantly get the error message

```
github.GithubException.RateLimitExceededException: 403 {"message":
"API rate limit exceeded for xx.xxx.xx.xx. (But here's the 
good news: Authenticated requests get a higher rate limit. 
Check out the documentation for more details.)", 
"documentation_url": "https://developer.github.com/v3/#rate-limiting"}
```

## Analysis

- ~~create some hackmd with brief analysis e.g. compare traffic a month ago with today; analyse on what pages do users bounce etc..~~ --> decided to create a small dashboard / traffic report with google data studio 

~~## Dashboard (in progress)~~

~~https://datastudio.google.com/s/uzd_szEi7rg~~

## Script for getting key repo metrics

https://github.com/frictionlessdata/pm-metrics

**Comment by monikappv** [comment]
started to build a small FD traffic dashboard - see https://datastudio.google.com/s/uzd_szEi7rg.

It is going to contain:
1. important Google Analytics numbers 
2. FD repos numbers (will build a pipeline script --> spreadsheet --> data studio) 

so we have everything in one place.

**Comment by rufuspollock** [comment]
@monikappv i don't think the acceptance criteria is clear enough here. I also thought this included git repo metrics as well as website traffic.

**Comment by monikappv** [comment]
@rufuspollock it will include exactly this.. this report should show the repos metrics (which we currently get as a csv --> not so useful) + site traffic data from google analytics.

**Comment by rufuspollock** [comment]
@monikappv csv is fine for now!

**Comment by rufuspollock** [comment]
@monikappv can we prioritize shipping this today - just as CSV. You can push it into this repo i think in a subfolder.

**Comment by monikappv** [comment]
@rufuspollock here is the CSV file containing the FD repositories key traffic metrics https://github.com/frictionlessdata/project/tree/master/metrics-track.

and here is a screenshot of the csv file

![repos-preview](https://user-images.githubusercontent.com/56799741/82230559-88c23700-9934-11ea-8571-c12aa425dabb.png)

**NB:** currently number of watchers = number of stars for each repo (it is like this also in the source). I found a solution, see 1st bullet point in *"Outstanding"* below.

## Outstanding
I am planning to 

* fix watchers numbers (it is inaccurate also in the source a.k.a github API - `watchers_count` as well as the `watchers` number are same as the `stargazers_count`). However, after having a deeper look at this, I found a variable in the API called `subscribers_count` that overlaps with the actual watchers number shown in the repos.
* push this as a data package in a repo somewhere (e.g. frictionlessdata/repos-metrics)? Let me know if you would like me to do that.

**Comment by rufuspollock** [comment]
@monikappv  👏  - great. Let's get subscribers_count done and agree on pushing to a separate repo. 👍 on data packaging this and I think calling repo `pm-metrics` might be good with a short description of what this is (this avoid confusion that this is a tool for doing metrics).

**Comment by rufuspollock** [comment]
@monikappv can we now close this? What's remaining?

**Comment by monikappv** [comment]
@rufuspollock had some issues with the subscribers_count and then with the token - it was constantly throwing an error 'API rate limit exceeded for xx.xxx.xx.xx.' even if I run it once per day. obviously my approach was a bit wrong, so I fixed it.

**Comment by monikappv** [comment]
FIXED.

We now have it right and get the accurate watchers count.

1. The wanted CSV file is called `fd-repos-metrics.csv` and is in a new repo https://github.com/frictionlessdata/pm-metrics. 
2. In the repo there is also the whole thing data packaged - ready to be applied to other github users/orgs.
