### ISSUE TITLE
Community feedback - things to work on to improve FD

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#493]
**Main Questions:** 
1. What's the most important thing to work on to improve Frictionless Data?
2. What are the key things people look at when evaluating whether to use or not FD tools?

**Purpose:** Help adoption of FD / Improve FD based on community's feedback.

## Acceptance

* [ ] there is a plan of action for things that need to be improved based on people's feedback

## Tasks

* [ ] gather community people's opinions
* [ ] create a list of things that need to be improved
* [ ] generate action for each thing 
* [ ] ...

## Improvements suggested by people

* infer for csv files (frictionless data tool, that starting from a CSV file create a basic CSV Dialect spec file that has inside the field separator) @aborruso https://github.com/frictionlessdata/forum/issues/25

## Feedback from May community Hangout
- Links for personas with a short article about what they would get
- Add “(Data) Developer” to list of personas
   - Maybe add data analyst
- Diagram 
    - Diagram showing how specs fit together – see http://tech.datopian.com/frictionless/
    - Diagram showing what mapping to FD exist e.g. Format X => FD, FD => Format Y
    - Dig out old diagram showing the m2m … as a useful illustration (https://old.frictionlessdata.io/)
    - Hexagons are useful (but maybe a bit complex - maybe we can simplify)

**Comment by sglavoie** [comment]
**WONTFIX**: Closing because we can take advantage of the new Discussions feature on GitHub and we ask people for their feedback during each community call. We can now also link to the [Discussions tab](https://github.com/frictionlessdata/project/discussions) for this project.

**Comment by rufuspollock** [comment]
@sglavoie the discussions feature and this are unrelated. Reopening.

**Comment by lwinfree** [comment]
Closing as we've gotten user feedback this in various ways since this issue was created (docs, tutorials, website, applications, survey)
