### ISSUE TITLE
[epic] HowTos

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#495]
Have a bunch of howtos on the website and a process for adding new ones.

## Acceptance

* [ ] 3+ howtos on the site
* [x] Backlog of howtos to create
* [ ] Simple way to add howtos to site that is documented in e.g. contributing

## Tasks

* [x] Brainstorm backlog of howtos **DONE https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1272791416 **
* [x] Template for howtos and process for creating (e.g. is it a jupyter notebook)
* [x] Write 2-3 howtos #453
* [ ] Put these on the website
* [ ] Write more ...
* [ ] ...

**Comment by lwinfree** [comment]
May 18 update: 
- 5 how-to's written
- https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1272791416

To Do:
- Evgeny will work on putting them on the site
- Evgeny & Lilly can write up the process for getting them on the site for other contributors
- Lilly to write elastic search & amazon redshift how tos

**Comment by roll** [comment]
We can merge this issue with a high-level https://github.com/frictionlessdata/project/issues/542 as we're going to add a lot of documents like "Working with SQL in Frictionless" etc

**Comment by rufuspollock** [comment]
@lwinfree @roll do you think we can close this in favour of e.g. #542 and work on frictionless python lib (perhaps with a bit of detail of what has been done)?

**Comment by lwinfree** [comment]
yes!
