### ISSUE TITLE
Complete the new march 2020 issue tree ...

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#496]
Have a completed issue tree with the analysis done.

## Acceptance

* [x] Complete issue tree analysis https://docs.google.com/spreadsheets/d/1Hrm4F6OxVEeMxvXfMt_wKuLSKgFhVvibeEGBEmLMH3c/edit#gid=1855045926

## Tasks

* [x] Add High Level Goals to spreadsheet
* [x] Review each question and update the status for them

**Comment by lauragift21** [comment]
DONE. See https://docs.google.com/spreadsheets/d/1Hrm4F6OxVEeMxvXfMt_wKuLSKgFhVvibeEGBEmLMH3c/edit#gid=1855045926

The cells with a status of less than 100% are still ongoing items.
