### ISSUE TITLE
Frictionless Fridays experiment - e.g. 3pm CET

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#500]
Organize Frictionless Fridays office hours on Discord where community members can ask the core team questions about FD.

## Acceptance Criteria

* [x] we have done two sessions of this.

## Tasks
  * [x] Announce on discord with date and time
 * [x] Hold at least two sessions

**Comment by rufuspollock** [comment]
@lauragift21 can you fill this in with description, acceptance, tasks etc (remember this is for the "experiment" e.g. first 2 sessions).

Also can you put a comment update on how last friday went e.g. did people come, was it useful etc.

**Comment by lauragift21** [comment]
## Recap from our first Frictionless Fridays session
We had questions from two community members and Lilly and I was available on chat to help answer these question. It was useful because we had the chance to hear from our users and their pain points and we also helped them clarify some of the questions.

**Comment by lauragift21** [comment]
## Second time running Frictionless Fridays sessions

We did not have any questions or community members with any inquiries.

**Comment by lwinfree** [comment]
My opinion after doing 2 sessions is that I like this format & am happy to continue. I predict that we will sometimes have lots of questions and sometimes have no questions, and I think that is fine. What do others think?

**Comment by lauragift21** [comment]
Yes, I do too and I think we should continue.

**Comment by lauragift21** [comment]
FIXED. Frictionless Fridays was a great idea! we will continue having it.

**Comment by lwinfree** [comment]
Hey @rufuspollock & @lauragift21 I think we should open this again to have a discussion. The way Frictionless Fridays was done today is not the way we agreed to do it/have done it in the past. I think it works well how it was originally agreed upon (that is - office hours where users can come & ask questions) works really well. I don't think it makes sense to add in a call where people are tasked with work to do. If you want to have a coworking hour, I think it should happen at a different time and not take over Frictionless Fridays. What do y'all think?

**Comment by rufuspollock** [comment]
@lwinfree can you say more about the issue for you?

The logic of this at my end (for myself and datopian folks) was that if we are around to answer any questions that come up during Q&A we may as well do some coworking - and it's a great chance to do that and have some activity. I'm not sure it will happen every time - but when people are around we may as well do it for the people who want to ...

I also think it unlikely that we have the resource / energy to have 2 times atm.

**Comment by lwinfree** [comment]
@rufuspollock the logic is that we agreed to do 1 thing, and all decided it was working, and then you did something totally different and pressured people to join the new task. I am fine with coworking, but it should not overwhelm the initial event (which is what happened). One of the great things about #FF (as we agreed to do it) is that Gift & I are the only ones that need be present - so you and the other team members that want to cowork can cowork another time, so you won't be stretched to do 2 things a week.

**Comment by rufuspollock** [comment]
@lwinfree i kind of object to saying people were pressured ... I discussed this with Monika, Gift and Sebastien previous week and carles and jen-thomas specifically said they wanted to join in.

I don't see this as totally different: it is people hanging out during that time and answering questions if people are there *and* some of those people (who agreed to it) doing some co-working.

I suggest we get on a short call to get this flat 😄
