### ISSUE TITLE
Frictionless Data Events Page

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/frictionlessdata.io#501]
We want to have a page with a listing of upcoming Frictionless Data events.

- When I visit the Frictionless Data website I want to be able to view a list of upcoming events so that I can register/signup for those events. 

## Acceptance

* [x] we have a section listing all of our events

## Tasks

* [x] boot a google calendar e.g. "Frictionless Public" 
* [x] embedding that - we could also link to a tag from the blog (or even embed) for things like the hangouts.

**Comment by lauragift21** [comment]
FIXED. I embedded a calendar with our scheduled events on the website and a link to all events tags on our blog.
