### ISSUE TITLE
May 2020 Virtual Community Hangout

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#506]
Our next 1h community hangout to chat about recent developments in Frictionless and data generally and next steps. Invite community members to it ...

Organizer: @lauragift21 (Datopian) and @lwinfree (OKF)

Date: 21st May 5pm BST 

## Agenda (in progress)

* Welcome
* Updates
* Mention our social media frictionlessd8a
* Next meeting for June https://forms.gle/5HeMrt2MDCYSYWxT8
* Community announcements / sharing
* Opportunities to contribute - see the forum and "good first issue" https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

## Acceptance

* [x] Blog post for the hangout (where we can also post updates afterwards) https://frictionlessdata.io/blog/2020/05/20/frictionless-data-may-hangout/
* [x] Announce on social media, x-post on blog.okfn.org and datopian.com and datahub.io (?)
* [x] An awesome 🎉 1h community hangout with at least 15 participants
* [x] Material prepped re how people can contribute

## Tasks

* [x] Landing page / blog post (with tag `Events` and `community hangout`)
* [x] Zoom call link
* [x] Announce on social media
* [x] Schedule June meeting
* [x] Create google form for people to sign up to come
  * Name, Email
  * Comment: Suggestion for topics to cover, something you want to share
  * An opt-in "keep me up to date with news (lesss than once a month)" so people could opt-in to newsletter
* [x] Look through and label / create a few "good first task" items and mention this on call a put link
* [ ] Recording on YouTube
* [ ] Prep updates
  * [ ] schemas.frictionlessdata.io
  * [ ] blog post from the french guys ...

### People to invite

* [ ] @loleg 
* [ ] @Stephen-Gates 
* [ ] @johanricher
* [ ] @augusto-herrmann 
* [ ] @danielfireman 
* [ ] @Irio 
* [ ] @rufuspollock 
* [ ] @iSnow 
* [ ] @stephanmax 
* [ ] @andrejjh 
* [ ] @switzersc 
* [ ] @kleanthisk10 
* [ ] @monsauce
* [ ] @lilyzzhao
* [ ] @ousodaniel
* [ ] @seleneyang
* [ ] @roll 
* [ ] @amercader 
* [ ] @jobarratt 
* [ ] @chris
* [ ] @akariv 
* [ ] @georgeslabreche 
* [ ] @cblop
* [ ] @OriHoch 
* [ ] @pwalsh 
* [ ] @chris48s

**Comment by ousodaniel** [comment]
Thanks @rufuspollock, planning to be there

**Comment by lwinfree** [comment]
@lauragift21 this will be at 5pm BST, right? It says 5pm CET above. Thx!

**Comment by lauragift21** [comment]
Yes, thanks for pointing that out @lwinfree.

**Comment by augusto-herrmann** [comment]
Cool! Where do I find the link for participation?

**Comment by lwinfree** [comment]
@augusto-herrmann register here :-) https://us02web.zoom.us/meeting/register/tZMsf-qrrjopHtGZwMyM7tCmp_YyPlNms6wK

**Comment by augusto-herrmann** [comment]
Too bad I didn't see it in time. :cry:

**Comment by lwinfree** [comment]
@augusto-herrmann these will be happening once a month, so hopefully you can join the next one! We announce them in Discord too (join here: https://discord.gg/2UgfM2k).

**Comment by rufuspollock** [comment]
@lauragift21 can we close this now? Is the video added to the blog post?

**Comment by sglavoie** [comment]
@rufuspollock: we have a Zoom recording for this hangout. Would you like me to add it to the [blog post](https://frictionlessdata.io/blog/2020/05/20/frictionless-data-may-hangout/) and then close this issue?

**Comment by rufuspollock** [comment]
@sglavoie yes, please!

**Comment by rufuspollock** [comment]
FIXED. (Assuming @sglavoie adds the recording to the post).
