### ISSUE TITLE
Community Hangout - 25 June 2020

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#507]
Our next 1h community hangout to chat about recent developments in Frictionless and data generally and next steps. Invite community members to it ...

Organizer: @lauragift21 (Datopian) and @lwinfree (OKF)

Date: 25th June 5pm BST 

## Agenda (in progress)

* Welcome
* Updates
* Social media frictionlessd8a
* Next meeting for July https://forms.gle/5HeMrt2MDCYSYWxT8
* Community Announcements/sharing
* Opportunities to contribute - see the forum and "good first issue" https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

## Acceptance

* [x] Blog post for the hangout (where we can also post updates afterwards) https://frictionlessdata.io/blog/2020/06/05/june-virtual-hangout/
* [x] Announce on social media, x-post on blog.okfn.org and datopian.com and datahub.io (?)
* [x] An awesome 🎉 1h community hangout with at least 15 participants
* [x] Material prepped re how people can contribute

## Tasks

* [x] Zoom call link
* [x] Announce on social media
* [x] Schedule July meeting https://us02web.zoom.us/j/84638060428?pwd=NEppT2FsQVk3dk1EUEgyYWpJRmxtQT09
* [x] Recording on YouTube. https://www.youtube.com/watch?v=xBu855rFiOM&t=210s

**Comment by lauragift21** [comment]
FIXED. we've had hangout and recording is up on YouTube.
