### ISSUE TITLE
Move relevant content from software repo here

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#509]
https://github.com/frictionlessdata/software has a bunch of relevant content e.g. implementation reference (in README), libraries status overview (STATUS.md). We want to revi

NB: `software` repo is already archived and is read-only.

## Acceptance

* [x] Assessment done
* [x] Everything moved

## Tasks

* [x] README.md  - Implementation Reference **MOVED to an rfc in this repo https://github.com/frictionlessdata/project/blob/master/rfcs/0003-library-implementation-reference.md**
* [x] PROCESS.md - implementation "governance" process **LEAVE/OBSOLETE - a bit unfinished, was more aspirational, and now out of date (I think)**
* [x]  STATUS.md - list of libraries with their build status etc **MOVED to README in this repo https://github.com/frictionlessdata/project#libraries-status**
* [x] TEAMS.md - list of libraries with their rough owner **LEAVE - a bit repetitive and easy to be out of date. Also better to use https://frictionlessdata.io/team/**
* [x] scripts/ there are some scripts for generating e.g. teams and status **LEAVE. i think we can maintain by hand for now. If we need in future we can come back**

**Comment by rufuspollock** [comment]
FIXED. See description for the updates.
