### ISSUE TITLE
RFC process

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#510]
We've started moving some substantive items to an rfcs folder in this repo. It would be good to explain RFC process and approach.

## Acceptance

* [ ] RFC overview in README **DONE: see https://github.com/frictionlessdata/project/tree/master/rfcs**
* [ ] RFC template **DONE: see https://github.com/frictionlessdata/project/blob/master/rfcs/0000-template.md**

## Tasks

* [x] Dig out rfcs guidelines e.g. https://github.com/vuejs/rfcs and extract relevant parts
* [x] Find a template

**Comment by rufuspollock** [comment]
FIXED.

Note: with the existence of github discussions i wonder if going forward we could just use discussions for proposing and discussing RFCs and then, if necessary, move agreed version to rfc folder. (I notice nextjs use github discussions in this way for RFCs)
