### ISSUE TITLE
Make the discord link on the site more prominent

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/frictionlessdata.io#512]
Make the discord link more prominent (like they have it in other sites e.g. in https://www.gatsbyjs.org/ - it has a nice little menu of key links e.g. discord, gitter etc)

When we want to increase our community, we want to make the key links (discord, gitter) on the site more prominent, so that we can be easily seen / found / visited.

## Acceptance 

* [x] the discord link works on the site
* [x] the discord (and other key links) look more prominent and with an icon

## Tasks

* [x] check if the discord link works :heavy_check_mark: 
* [x] copy the svg-s from gatsbyjs.org 
* [x] override the default Navbar.vue component by copying it from `sandbox`, adding it to our components and editing it 
* [x] add icons
* [x] do some css adjustments e.g. color change on hover; padding from top etc.
* [x] push the changes
* [x] test if the links work :heavy_check_mark: 

## New look

![navIcons_fd](https://user-images.githubusercontent.com/56799741/83019374-84ca9f00-a02f-11ea-898c-72f44884f2db.png)

**Comment by monikappv** [comment]
FIXED.

See 'New look' section in issue description or live on https://frictionlessdata.io/.

**Comment by rufuspollock** [comment]
@monikappv 👏really nice - btw could we get a github link to the project repo (and btw are the links configurable from the vuepress js config file?

**Comment by lauragift21** [comment]
@monikappv looks really nice.👏 I see the logo bug now reflects in prod. When I try scrolling it's not fixed.

**Comment by monikappv** [comment]
@rufuspollock made them configurable from the config file 
![navbar_links_FD](https://user-images.githubusercontent.com/56799741/83034918-771e1500-a041-11ea-94a1-b3285fb80096.png)

also added a GitHub link and switched the positions of the navlinks and the search bar + the icons (like they have it on gatsby)
![more_like_gatsby](https://user-images.githubusercontent.com/56799741/83034984-8c933f00-a041-11ea-8de1-962178060876.png)

**not sure what's better...any thoughts?**

@lauragift21 I changed the vertical alignment of the logo while playing with the navbar but didn't help so i brought back the prev settings. haven't really dedicated time on fixing it - If you want we can have a quick pair session and rubber duck cause it's been a while since the bug exists.

**Comment by augusto-herrmann** [comment]
I thought only gaming communities used Discord. Can I ask why you're using it instead of some open source [alternative](https://alternativeto.net/software/discord-app/)?

**Comment by rufuspollock** [comment]
@augusto-herrmann discord whilst starting in gaming is now heavily used by tech communities  e.g. many react communities use it, https://www.gatsbyjs.org/ uses it, gridsome uses it etc. Can you specify *which* open source alternative you would recommend? By default i would prefer open source *if* it is matching or close to matching on key features and 0 cost.

PS  the best thread for this is https://github.com/frictionlessdata/forum/issues/13 - this issue is about website update ...
