### ISSUE TITLE
[epic] Design System for Frictionless Data incl shape (hexagons etc)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#522]
Inbox

* [ ] Needs / job stories
* [ ] Hexagons as shape
* [ ] Toolbox with hexagons
* [ ] Steps (as hexagons)
* [ ] Are we overdoing hexagons

**Comment by lwinfree** [comment]
Closing as we've moved away from this design aesthetic
