### ISSUE TITLE
frictionless code of conduct

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#523]
Hi all! I am updating the OKF code of conduct (CoC) currently, and wanted to also work on one for FD. In the past, I have linked to the current OKF participation guidelines when I have led FD events as a proxy for a FD-specific CoC. My proposal is that we can use the updated OKF CoC for the FD CoC, or we can create a separate one for FD. We can also simply copy the text from the OKF one once it is done as it is CCBY4.0. I don't have a strong opinion either way. What do others think? Is anyone interested in working on this with me? *Note I can share the completed, updated OKF CoC soon*

## Tasks

* [x] decide on reusing OKF's CoC or creating a new one
* [x] create the CoC
* [x] put it on the FD site
* [x] put it on all the FD repos (link in the readme?)

**Comment by lwinfree** [comment]
also, here is the CKAN CoC, which looks good in my opinion: https://github.com/ckan/ckan/blob/master/CODE_OF_CONDUCT.md

**Comment by lwinfree** [comment]
Here is the OKF code of conduct, which we will re-use for FD: https://okfn.org/about/code-of-conduct/
