### ISSUE TITLE
Merge forum to this repo

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#525]
In spirit of "one" way to do things if possible, let's move forum (https://github.com/frictionlessdata/forum) stuff here and track it.

## Acceptance

* [x] Forum issues moved here and redirect __Done__ https://github.com/frictionlessdata/project/issues
* [x] Forum deprecated __Done__ https://github.com/frictionlessdata/project/pull/575
* [x] Some info in README (stuff from README) __Done__ https://github.com/frictionlessdata/project/pull/575
* [x] Update Overview board in this repo with same info as in forum. __Done__ https://github.com/frictionlessdata/project/projects/3

## Tasks

* [x] Transfer all issues from (https://github.com/frictionlessdata/forum) to this repo.
  * [x] Set the same labels, project and status (In Progress, Done, etc.) for each one. – **DONE**: We used the screenshot below as a reference and moved the whole project keeping the same information about labels and statuses.
* [x] Move relevant content from https://github.com/frictionlessdata/forum/blob/master/README.md to https://github.com/frictionlessdata/project/blob/master/README.md.

## Analysis

![2020-11-10_08-25](https://user-images.githubusercontent.com/32682903/98687295-3126e600-232f-11eb-9896-27cfbc551b7b.png)

**Comment by lwinfree** [comment]
tagging @roll. We talked about merging the forum issue tracker into this issue tracker so that there is only 1 tracker. Do you have thoughts about that Evgeny?

**Comment by roll** [comment]
Cool but what about Github Discussions?

**Comment by sglavoie** [comment]
**WONTFIX**: Closing because there is a new feature called "Discussions" which we will use instead.

**Comment by rufuspollock** [comment]
@sglavoie as discussed on call today we still need to do this merge! Even if we have discussions. I suggest this is something @yaso could take on.

**Comment by risenW** [comment]
@rufuspollock care to throw more light on acceptance criteria 3-Some info in README (stuff from README)

**Comment by rufuspollock** [comment]
@risenW i meant to update forum repo README to indicate it had moved here and was deprecated.

**Comment by risenW** [comment]
> @risenW i meant to update forum repo README to indicate it had moved here and was deprecated.

Okay, got it. @sglavoie already fixed it here ==> https://github.com/frictionlessdata/project/pull/575

**Comment by rufuspollock** [comment]
INVALID / WONTFIX / FIXED (partial). This got obsoleted by existence of github discussions and now have a successor issue in #581.
