### ISSUE TITLE
Community Hangout - 27 August 2020

### ISSUE THREAD

**Issue by sglavoie** [frictionlessdata/frictionlessdata.io#531]
Our next 1h community hangout to chat about recent developments in Frictionless and data generally and next steps. Invite community members to it ...

Organizer: @sglavoie (Datopian) and @lwinfree (OKF)

Date: **27<sup>th</sup> August 5pm BST** 

## Agenda

* Welcome and introductions: Icebreaker! [10m]
* Link to meeting doc
* Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a) and [Discord Channel](https://discordapp.com/invite/Sewv6av)
* Any items for the agenda?
* Updates
  * frictionless-py — [frictionlessdata/frictionless-py](https://github.com/frictionlessdata/frictionless-py): Frictionless for Python is a framework to describe, extract, validate, and transform tabular data.
    * We have a nice video presentation sent by none other than the technical lead working on the project, Evgeny!
  * @chrispomeroyhale has been working on 2 frictionless Swift libraries! You can check them out here: https://github.com/frictionlessdata/datapackage-swift and here: https://github.com/frictionlessdata/tableschema-swift They are also on the Swift Package Directory (https://www.swiftpackage.directory/) and Swift Package Index (https://swiftpackageindex.com/frictionlessdata/datapackage-swift) too
* Updates from Lilly: Reproducible Research Fellows Programme & Tool Fund
* Community announcements/sharing
  * Opportunities to contribute - see the forum and "[good first issue](https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)"
* Discussion
  * Google Analytics vs [GoatCounter](https://www.goatcounter.com/) vs [Matomo](https://matomo.org) vs … @loleg's expertise welcome! :slightly_smiling_face: 
    * [Suggestion: replace Google Analytics by GoatCounter #532](https://github.com/frictionlessdata/project/issues/532) (GitHub).
* AOB
  * Next meeting for September https://forms.gle/5HeMrt2MDCYSYWxT8
* Frictionless-py questions/comments/feedback

## Acceptance

* [x] Blog post for the hangout (where we can also post updates afterwards) — **DONE**: https://frictionlessdata.io/blog/2020/08/27/august-virtual-hangout/
* [x] Announce on social media
* [x] x-post on blog.okfn.org and datopian.com and datahub.io (?) – **DONE**: https://blog.okfn.org/2020/08/24/frictionless-data-monthly-virtual-hangout-27-august/
* [ ] An awesome 🎉 1h community hangout with at least 15 participants – Awesome: Yes :sunglasses:. 1h: roughly. 15 participants: 8 officially joined. We'll share more on YouTube, blog about it and let people know what we were up to on Twitter and Discord to reach the rest of the community. :muscle: 
* [x] Material prepped re how people can contribute – **DONE**: We have a [list of separated issues](https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and Rufus Pollock showed a great overview during the meeting of the tools we are working on, letting people know that their contributions are welcome any time.

## Tasks

* [x] Update RSVP form with the correct hangout date. — **DONE**: https://forms.gle/3wEGBy2q4Q6pdNfK8
* [x] Zoom call link
  * [x] Email guests ~2-3h before the event with the meeting details.
  * [x] Send meeting link ~10 minutes before the event on Discord.
* [x] Add previous guests to the Google Calendar invite
* [x] Create a new entry in the public meeting doc with agenda for this hangout.
* [x] Announce on Twitter
  * [x] Tue 25 August
  * [x] Early Thu 27 August
* [x] Send reminders on Discord
  * [x] Mon 24 August
  * ~~Wed 26 August~~ (barely any messages were added to the channel, this will be more spammy than anything else)
* [x] Schedule September Zoom meeting – **DONE**: 
* [x] Recording on YouTube.
  * [x] Update blog post with link to YouTube video.

**Comment by loleg** [comment]
I've been using, [integrating](https://github.com/hackathons-ftw/dribdat/pull/162), involved in discussions with https://usefathom.com/ happy to add my 2 cents to the Analytics discussion. In fact I've had thoughts about promoting more open analytics data [for a while](https://speakerdeck.com/loleg/information-architecture?slide=22).

**Comment by sglavoie** [comment]
Thank you @loleg! Your point of view as a veteran on this topic will definitely be welcome! I am sure we will all benefit from your presence if you can make it (and it looks like a *yes* from the calendar :wink:).

**Comment by sglavoie** [comment]
**FIXED**: Closing as all tasks were completed, nothing else needs to be done for this issue.
