### ISSUE TITLE
Suggestion: replace Google Analytics by GoatCounter

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/frictionlessdata.io#532]
I just opened a ticket like this but now it's gone - I'm typing it again. If you find a duplicate somewhere feel free to close one of them.

FrictionlessData websites like https://frictionlessdata.io/ and https://create.frictionlessdata.io/ use Google Analytics. I suggest to use https://www.goatcounter.com/ : an open source, no tracking of personal data, hosted service (free for non-commercial use) alternative.

The reason that I suggest this replacement is to help our users to not pass data to Google Analytics and also to promote and support Open Source alternatives. Bonus point: GoatCounter has an export functionality and they could also provide the tableschema in the future :-)

If the change is not possible because GoatCounter lacks of some functionality needed by FD it would be nice to open an issue(s) in case that it could be implemented in the future: https://github.com/zgoat/goatcounter

Job story (feel free to change this, I'm not involved in the FD web):

## Acceptance

* [ ] Google Analytics is removed from frictionlessdata.io and create.frictionlessdata.io
* [ ] GoatCounter is added

## Tasks

* [ ] Evaluate if GoatCounter has enough functionality for Frictionless Data needed analytics
* [ ] Install GoatCounter in the websites (with Google Analytics? To compare results for a while?)
* [ ] Export data from Google Analytics? (I don't know if this is possible)
* [ ] Remove Google Analytics

---

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by akuckartz** [comment]
Matomo?

**Comment by cpina** [comment]
> Matomo?

I think that to use Matomo (https://matomo.org) there are two possible ways to go:
 * Self-hosted in a Frictionless server (setup, maintenance for Frictionless)
 * Hosted by Matomo: monthly subscription (https://matomo.org/pricing/) (21 day for free)

For Goatcounter (https://www.goatcounter.com/):
 * Self-hosted (implemented in Go and Postgresql, not sure if it requires Postgresql or can use other DBs)
 * Hosted by Goatcounter: it's free for non-commercial usage: Frictionless could use this.

I suggested Goatcounter in case that it's enough and Frictionless could use it for free and hosted by Goatcounter (so no extra servers to maintain for the project).

As a side note, Goatcounter doesn't use cookies for session tracking (https://github.com/zgoat/goatcounter/blob/master/docs/sessions.markdown , it uses a non-identifiable hash) and Matomo I think that uses cookies. I find this kind of nice :-) I haven't looked at how good is Goatcounter or if Matomo can use non-identifiable hash.

Either way, I would prefer Matomo or Goatcounter to Google Analytics if possible.

**Comment by arp242** [comment]
> Self-hosted (implemented in Go and Postgresql, not sure if it requires Postgresql or can use other DBs)

It supports SQLite and PostgreSQL; for a single site, SQLite should be "good enough" for almost all use cases; in the benchmarks I ran last year it was actually *faster* than PostgreSQL.

> As a side note, Goatcounter doesn't use cookies for session tracking (https://github.com/zgoat/goatcounter/blob/master/docs/sessions.markdown , it uses a non-identifiable hash

Also, this hash doesn't gets stored to disk; it's just an in-memory thing more similar to TCP sessions or some such than anything else.

Anyway, Matomo is cool too, and can certainly do a bunch of stuff GoatCounter can't (not yet, anyway) :-)

**Comment by cpina** [comment]
I couldn't make it to the community call... Were there any discussions about this topic? (@loleg / @sglavoie ) I'd like to know more. Thanks!

**Comment by sglavoie** [comment]
Hi @cpina!

* The video has been [uploaded here](https://youtu.be/HezM-DPB2v4?t=1841). (This is the timestamp at which the conversation on analytics starts).
* You can also see the agenda and other items of interest on [this blog post](https://frictionlessdata.io/blog/2020/08/27/august-virtual-hangout/#community-hangout-recording).
* I think there is still a lot of space for discussion if we want to go further down that path. You are most definitely welcome to bring the topic this month if you can make it (still to be announced, it should be on Thu 24 September, 5pm BST as usual) :wink:.

**Comment by cpina** [comment]
Hi @sglavoie  - Thanks for the link, I'll watch the video and I'll comment further if needed. I should be able to join on the 24th September (noted into the calendar) as well in case that I would like to comment there. Cheers!

**Comment by cpina** [comment]
@sglavoie , @loleg: I've just watched the part of the community call that you talked about analytics (I'll listen to the rest soon). Thanks for presenting the tools and the clear explanation. When I opened this issue I was not thinking on promoting "open data analytics" for open projects but I was thinking on supporting other open source projects (GoatCounter, Matomo, etc.) and helping users to be private with privacy oriented statistic software/services. So it was a good additional angle! thanks!

(I do remember the counter of people on the websites; I even remember implementing a basic version for a website)

Some questions are still in the air: would Frictionlessdata like to leave Google Analytics and move to an alternative open source and more private solution? is there any question that needs to be answered?Is there any missing feature that should be available to the other tools? (I just don't know how is the Google Analytics data used in Frictionnlessdata).

Thanks again for the discussion!

**Comment by rufuspollock** [comment]
For me this has really low priority vs many other tasks that deliver immediate value to the project (most important of which the move to new library structure) 😄 

I'd suggest we only come back to this if/when we've made demonstrable progress there.

**Comment by lwinfree** [comment]
@cpina We don't use analytics very often actually. In the past year, we've used it to help inform the website redesign (seeing which pages users spend time on/how users flow thru the website) and to get user stats for applying for more funding :-) 

I agree with @rufuspollock that maybe we can table making a decision on this until the next time we need to use analytics for something. At that point, I would definitely be interested in playing around with GoatCounter (or something else open) to see if it provides us with the info we need. I'm going to close this issue as I don't think there are immediate actions now, but I am definitely still interested in this idea in the future!
