### ISSUE TITLE
Community Hangout - 22 October 2020

### ISSUE THREAD

**Issue by sglavoie** [frictionlessdata/frictionlessdata.io#536]
Our next 1h community hangout to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizer: @sglavoie (Datopian) and @lwinfree (OKF)

Date: **22<sup>th</sup> October, 5pm BST** 

## Agenda

* Welcome and introductions: Icebreaker! [10m]
* Link to meeting doc
* Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a) and [Discord Channel](https://discordapp.com/invite/Sewv6av)
* Any items for the agenda?
* Updates
  * frictionless-py — [frictionlessdata/frictionless-py](https://github.com/frictionlessdata/frictionless-py): Frictionless for Python is a framework to describe, extract, validate, and transform tabular data.
* Community announcements/sharing
  * Opportunities to contribute - see the forum and "[good first issue](https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)"
  * Keith: using frictionless to create infrastructure for sharing biology/genomics data packages.
* Discussion
  * Frictionless-py questions/comments/feedback
* AOB
  * Next meeting for November [link to be added]

## Acceptance

* [x] Blog post for the hangout (where we can also post updates afterwards) – **DONE**: https://frictionlessdata.io/blog/2020/10/28/october-virtual-hangout/
* [x] Announce on social media
* [x] Material prepped re how people can contribute.
* [ ] An awesome 🎉 1h community hangout with at least 15 participants – **Update**: We had a great presentation from a new member! However, there were technical difficulties with Zoom. The link was apparently not working for some people and the attendance was 7-8 members on the call. Put in place: promote the hangout internally at Datopian and make sure a link is shared with an embedded password to avoid the need for a waiting room.

## Tasks

* [x] Zoom call link
  * [x] Reserve slot in Zoom account.
  * [x] Email guests ~2-3h before the event with the meeting details.
* [x] Announce on Twitter – **DONE**: Oct 16 https://twitter.com/frictionlessd8a/status/1317090564140109825 + Oct 22 https://twitter.com/frictionlessd8a/status/1319252688534581250
* [x] Send reminders on Discord – **DONE**: See https://discord.com/channels/695635777199145130/695635777199145133
  * [x] Send meeting link ~10 minutes before the event on Discord.
* [x] Recording on YouTube. – **DONE**: [Keith's presentation](https://www.youtube.com/watch?v=GpIgfJE9UGw) and [the main event](https://www.youtube.com/watch?v=kZ4vy5zP0M0).
  * [x] Update blog post with link to YouTube video. – **DONE**: https://frictionlessdata.io/blog/2020/10/28/october-virtual-hangout/
* [x] Material prepped re how people can contribute. – **DONE**: Letting the community know they can vote here https://github.com/frictionlessdata/frictionless-py/issues/486, linking to https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 and pointing to social media accounts so people can stay engaged.
* [x] Schedule October Zoom meeting
* [x] Update RSVP form with the correct hangout date. – **DONE**: https://forms.gle/3wEGBy2q4Q6pdNfK8
* [x] Add previous guests to the Google Calendar invite
* [x] Create a new entry in the public meeting doc with agenda for this hangout.

**Comment by sglavoie** [comment]
**Note:** The step of generating the list of people to invite was automated internally to facilitate the task and to respect people's privacy by taking into account their selection from their last entry for the column "Keep me up to date". We generate a string of comma-separated emails that can be pasted straight into Gmail/Google Calendar.

**Comment by sglavoie** [comment]
### Tasks to add for next time

* Advertise the hangout internally: announcements channel, All Hands meeting, reminder through email.
* Make sure the **Google Meet** link is removed from the calendar. (This leads to confusion for some participants as there were two visible links one could join.)

**Comment by lwinfree** [comment]
I was thinking it might be cool to have @rufuspollock discuss the data views work at the next call. I think there are several groups that would find that interesting (including myself!). What do you think Rufus?

**Comment by sglavoie** [comment]
**FIXED**: Closing since we've had the community call and nothing more needs to be done specifically with this issue at this point – although further discussions are of course welcome! Issue for the next community call: #539.
