### ISSUE TITLE
Change project-wide terminology to be more inclusive

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionlessdata.io#537]
## Overview

This issue is to make a plan for removing/replacing internal terminology to be more inclusive. For example, changing the branch “master” to “main”. GitHub recommends waiting until "later this year" to rename all master branches to main, so we will wait. Ideally, GitHub will release tooling that makes this process smooth, so we will wait a bit and see. In the meantime, we are making lists of changes we want to make and identifying repos that need to be changed. We'll use this issue as a timeline and plan.

## Resources:
Feel free to add more resources.
- Guidance from GitHub: https://github.com/github/renaming
- https://www.zdnet.com/article/mysql-drops-master-slave-and-blacklist-whitelist-terminology/
- https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

## Acceptance

* [x] all of the changes from our list (below) have been made in all identified repos (note: this will take a while to finish)

## Tasks

* [x] choose a repository to test making these changes
* [x] make a list of changes to make (i.e. master to main; blacklist to denylist/prohibited value)
* [x] make a list of dependencies that would also need to change
* [x] make a list of repos to target to make these changes

**Comment by lwinfree** [comment]
(comments copied (& edited) from @chris48s via slack convo)

* Changing whitelist/blacklist to greenlist/redlist or allowlist/denylist is not usually a big change as long as its only used in the internals of a codebase. If its exposed in a public API surface, it's a breaking/non-BC change which requires a major version bump and should be co-ordinated with other non-BC changes.

* For any repo where you want to rename the default branch, you need to understand the list of external services that repo integrates with and what changes are needed (or not needed) elsewhere to account for it, otherwise you'll find your code coverage stops updating, your DockerHub builds stop running, or whatever.

* (re GitHub's recommendation:) I'm not sure what that tooling is going to look like and I expect when it comes to external integrations GH's scope to act is limited but I'm at least waiting to see how that plays out on other projects I am involved in. I suspect it will definitely make things easier for orgs with lots of repos and projects more tied to the GH ecosystem (e.g: GH actions/pages/etc). I expect they'll also auto-retarget open PRs and stuff, but I expect they can not really help with the wider ecosystem considerations.

* GH have now changed the default branch name for newly created repos so any new projects we create will use main as the default branch as opposed to master and we can all be more mindful of terminology we choose in future.

* practicalities to consider:
  - Is there a difference in how we treat newly created code/projects vs what we do with code/projects that already exist?
  - If we're going to make changes to existing projects, what's the scope? (We have a lot of repos, but many are essentially dormant/abandoned. Where do we stop pulling the thread?)
  - Any work in this area needs to be recognised as a potentially time-consuming process and planned/budgeted accordingly. For many repos we maintain, non-trivial work/research may be involved
  - As far as possible we should take advantage of tooling (which is in the works from GH) to help us

**Comment by lwinfree** [comment]
I'm going to start looking into this with the [`toolfund` repo](https://github.com/frictionlessdata/toolfund). I'll update the to-do list &/or add more comments here as I make progress! Any suggestions/comments are welcome too :-)

**Comment by roll** [comment]
@lwinfree 
Currently done:
- renamed white/blacklists in the `frictionless-py`
- repositories using `main` instead of `master`:
  - https://github.com/frictionlessdata/project
  - https://github.com/frictionlessdata/components
  - https://github.com/frictionlessdata/frictionless-py
  - https://github.com/frictionlessdata/libraries
  - https://github.com/frictionlessdata/repository

**Comment by roll** [comment]
@lwinfree 
There are still a few active repositories using master - https://github.com/frictionlessdata

**Comment by roll** [comment]
From the libraries only PHP and R are on master

**Comment by lwinfree** [comment]
DONE
