### ISSUE TITLE
Community Hangout - 19 November 2020

### ISSUE THREAD

**Issue by sglavoie** [frictionlessdata/frictionlessdata.io#539]
Our next 1h community hangout to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizers: @lwinfree (OKF) & @sglavoie (Datopian)
Lead of the repo: @lwinfree (OKF)

Date: **19<sup>th</sup> November, 5pm BST** 

## Agenda

*   Welcome and introductions: Icebreaker! [10m]
    *   Link to meeting doc
    *   Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a) and [Discord Channel](https://discordapp.com/invite/Sewv6av)
    *   What’s your field of study?
*   Any items for the agenda? Feel free to share below!
*   Community announcements/sharing
    *   A presentation from **Costas**, the team leader of the [ISA2 Interoperability Test Bed Action](https://joinup.ec.europa.eu/collection/interoperability-test-bed-repository/solution/interoperability-test-bed) at the European Commission! Relevant links:
        *   [Table Schema](https://specs.frictionlessdata.io/table-schema/).
        *   Validators:  [XML](https://www.itb.ec.europa.eu/docs/guides/latest/validatingXML/), [RDF](https://www.itb.ec.europa.eu/docs/guides/latest/validatingRDF/), [JSON](https://www.itb.ec.europa.eu/docs/guides/latest/validatingJSON/) and [CSV](https://www.itb.ec.europa.eu/docs/guides/latest/validatingCSV/) (based on a fork of  [tableschema-java](https://github.com/frictionlessdata/tableschema-java)).
            *   [Generic CSV validator](https://www.itb.ec.europa.eu/csv/any/upload).
            *   [Validator for Table Schema definitions](https://www.itb.ec.europa.eu/json/tableschema/upload) (i.e. a service to validate the schemas themselves). – [News article](https://joinup.ec.europa.eu/collection/interoperability-test-bed-repository/solution/interoperability-test-bed/news/table-schema-validator) about it!
            *   Validator for [Kohesio](https://kohesio.eu/) (beta validator [here](https://www.itb.ec.europa.eu/csv/kohesio/upload)).
        *   [Conformance testing platform](https://www.itb.ec.europa.eu/itb/).
    *   Opportunities to contribute - see the forum and "[good first issue](https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)"
    *   Should we participate in Hacktoberfest next year?
    *   **Oleg**:
        *   geospatial data standards, coping with Covid, show off our platform for open data hackathons
*   AOB
    *   TBA: Next meeting for December
    * OKF is hiring! [Have a look here](https://okfn.org/about/jobs/) if you're interested in recommending someone or in applying. :sunglasses: 
    *   Looking forward to meeting with us next time? Let us know on Discord or Twitter!

## Acceptance

* [x] Blog post for the hangout (where we can also post updates afterwards)
* [x] Announce on social media + GChat.
* [x] Material prepped re how people can contribute.
* [ ] An awesome 🎉 1h community hangout with at least 15 participants. — _Note_: There were 12 participants and all of them have been actively participating! We had a great time. :sunglasses: 

## Tasks

* [x] Zoom call link.
  * [x] Reserve slot in Zoom account. – **DONE**.
  * [x] Email guests ~2-3h before the event with the meeting details. – **DONE**: Sent a few minutes before the actual hangout, but participants from earlier presentations were reminded a couple of days before that. Everyone who we expected to be there showed up. :+1: 
* [x] Announce on Twitter. – **DONE**: https://twitter.com/frictionlessd8a/status/1328786244885688322
* [x] Send reminders on Discord. – **DONE**: https://discord.com/channels/695635777199145130/695635777199145133/778343577503006720
  * [x] Send meeting link ~10 minutes before the event on Discord.
* [x] Announce in GChat (`#Announcements`) a few hours before the hangout. – **DONE**: Posted 30 minutes before the event.
* [x] Recording on YouTube.
  * [x] Update blog post with link to YouTube video. – **DONE**: https://frictionlessdata.io/blog/2020/11/19/november-virtual-hangout/
* [x] Material prepped re how people can contribute. – **DONE**: Letting the community know they can vote here https://github.com/frictionlessdata/frictionless-py/issues/486, linking to https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 and pointing to social media accounts so people can stay engaged.
* [x] Schedule December Zoom meeting. – **DONE**: Dec 17, 5pm GMT.
* [x] Update RSVP form with the correct hangout date. – **DONE**: Nov 19, 5pm GMT.
* [x] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!).  – **DONE**: retrieved from Google Sheets (linked to the Google Form).
  * [x] Notify guests by email about the calendar event – click the blue **Send** button when saving the event. – **DONE**: emails sent.
* [x] Create a new entry in the public meeting doc with agenda for this hangout. – **DONE**: New entry ready to be expanded with updates from Frictionless and the community.

**Comment by sglavoie** [comment]
**FIXED**: All tasks were done.
