### ISSUE TITLE
Organizing this forum (and triaging issues)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#564]
Having some structure to this forum would help us manage stuff as it comes in.

## Job Stories

When someone asks a question I want to make sure it gets answered so that they are helped

When new ideas/suggestions come in I want to triage them by topic and priority so that I can find them again, others can find them ...

## Acceptance

* [x] Have a process **See analysis below**
* [x] Have board and labels setup **Done. Labels created and board for ideas is here https://github.com/frictionlessdata/forum/projects/1**
* [x] Classified current issues **Done. All labels added and ideas in https://github.com/frictionlessdata/forum/projects/1**

## Tasks

* [x] Do an analysis of what is needed **See job stories and analysis below**
* [x] Create proposals for labels and board structure **See below**
* [x] Implement for questions
* [x] Implement for ideas
* [x] Classify existing issues

## Analysis

Two primary categorisations:

* Questions
* Ideas

In more detail

* Question (and Bugs)
  * How do i use X 
  * Can do i do Y
  * Speculation ...
* Idea/Suggestion
  * New App / Feature
  * Improvement to existing
  * Discussion (?)

### Topics

Common to both would be classification by topic. An initial list of topics would be:

* Specs
* Tools
* Apps
* Process
* Docs

### Question process

* Label stuff with question
* Regularly review
* If we did have board it would have these states
  * No responses ...
  * Resolved (FIXED)
  * Awaiting response (from them)
  * Awaiting answer

### Idea process

* Classify ideas using topics plus additional labels below
* Handle "state" via a board with usual states e.g. in progress, prioritized etc

Create the following dimensions and attributes as labels:

Size

* Small
* Medium
* Large
