### ISSUE TITLE
Frictionless (Data Package) <=> CKAN

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#574]
**Flagging existing repo here: https://github.com/frictionlessdata/ckan-datapackage-tools (a bit lacking in docs if someone wanted to help out 😄**

Quick recipe (maybe evolving into a lib) for mapping from CKAN metadata <=> Frictionless specs

Job story: When getting data in and out of CKAN I'm frequently using Frictionless formats and tools (its my default format for extraction from other systems) and I want to be able to do conversion to and from CKAN metadata structure so that I can do my work quickly and without having to dig through CKAN documentation.

Bigger context: frequently pulling data from other systems into CKAN -- and from CKAN into other systems. We want to use Frictionless as the intermediate format so we can convert MxN into M+N problem.

```
Frictioness   <=>     CKAN
---------------------------
Data Package  <=>   Dataset
Data Resource <=>   Resource
Table Schema  <=>   ?? (datastore resources can have schemas)
```

## Acceptance

* [x] Documentation  of CKAN metadata (e.g. in a spreadsheet)
* [x] Mapping against Frictionless specs
* [ ] Page / docs on website (reference?)
* [ ] Scripts / tooling for doing this

## Tasks

* [ ] Document CKAN metadata in spreadsheet e.g. here is resource https://github.com/ckan/ckan/blob/master/ckan/model/resource.py - note we have spreadsheet we could use here can use this https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=0
* [ ] Comparison / mapping of Frictionless <=> CKAN
* [ ] Simple script (python and/or JS) to convert (recipe / howto on f11s.com)

## Example Script

https://gist.github.com/rufuspollock/bd8ae3575950d180cce33da59c021299

```python
# python 3+
def convert_data_package_to_ckan_package(data_package):
    '''
    Documentation of CKAN metadata structure ...
    https://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.create.package_create
    https://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.create.resource_create
    '''
    out = dict(data_package)
    out['extras'] = []
    # special case atm
    # future look through all fields not in ckan special list
    if 'tableschema' in out:
        out['extras'].append({
            'key': 'tableschema',
            'value': json.dumps(out['tableschema'])
        })
    out['resources'] = [ convert_data_resource_to_ckan_resource(res)
        for res in out['resources']]
    return out

def convert_data_resource_to_ckan_resource(resource):
    out = dict(resource)
    out['url'] = out['path']
    del out['path']
    if 'bytes' in out:
        out['size'] = out['bytes']
    # flatten as json strings all nested data
    for k in out.keys():
        value = out[k]
        if (isinstance(value, list) or isinstance(value, dict)):
            out[k] = json.dumps(value)
    return out

import collections
def dict_merge(dct, merge_dct):
    '''Recursive dict merge. 
    '''
    for k, v in merge_dct.items():
        if (k in dct and isinstance(dct[k], dict)
                and isinstance(merge_dct[k], collections.Mapping)):
            dict_merge(dct[k], merge_dct[k])
        else:
            dct[k] = merge_dct[k]
    return dct
```
