### ISSUE TITLE
Community Hangout - 17 December 2020

### ISSUE THREAD

**Issue by sglavoie** [frictionlessdata/frictionlessdata.io#577]
Our next 1h community hangout to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizers: @lwinfree (OKF) & @sglavoie (Datopian) — TBC
Lead of the repo: @lwinfree (OKF)

Date: **17<sup>th</sup> December, 5pm BST** 

## Agenda

*   Welcome and introductions: Icebreaker! [10m]
    *   Link to meeting doc
    *   Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a) and [Discord Channel](https://discordapp.com/invite/Sewv6av)
    *   What’s your field of study?
*   Any items for the agenda? Feel free to share below!
*   Community announcements/sharing
    *   A presentation from [@ikreymer](https://github.com/ikreymer), about "_using frictionless data package for web archive data package (WACZ format)_". More details in this [GitHub issue](https://github.com/frictionlessdata/forum/issues/69).
        *   [https://github.com/webrecorder/wacz-format/tree/master/py-wacz](https://github.com/webrecorder/wacz-format/tree/master/py-wacz)
        *   [https://replayweb.page/](https://replayweb.page/) 
        *   Use cases?
            *   Journalists are a good one.
            *   Institutions that already do some form of archiving (museums, libraries…).
            *   Useful for any static storage and using “replay webpage” to replay the archive.
            *   [https://webarchive-demo2.glitch.me/](https://webarchive-demo2.glitch.me/) loading a web archive in an iframe for embedded content
            *   Archiving old web works
    *   Opportunities to contribute - see the forum and "[good first issue](https://github.com/frictionlessdata/project/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)". How can we improve the experience?
    *   Should we participate in Hacktoberfest next year?
*   Discussion
    *   People are interested in tools dealing with tools dealing with “small” data.
    *   What are we up to for 2021? What’s the roadmap for Frictionless?
        *   Specs are stable.
        *   Always bet on JavaScript! We will keep focusing on working with tools for JavaScript. Its versatility is required for desktop apps, using dynamic frameworks like React, etc.
            *   We will keep working on [https://github.com/frictionlessdata/frictionless-js](https://github.com/frictionlessdata/frictionless-js)
    *   [https://github.com/datopian/data-cli](https://github.com/datopian/data-cli) Command line tool for working with data, Data Packages and the DataHub
    *   [https://github.com/datopian/datapub](https://github.com/datopian/datapub) React-based framework for building data publishing workflows (esp for CKAN)
*   AOB
    *   TBA: Next meeting for January.
    *   Anything you’d like to discuss next time? Feel free to [fill your suggestions below](https://docs.google.com/document/d/1voVsjlTsiGHByAqEE7BSulrBArk7x_5EqI1CRLITynI/edit#heading=h.vadl54dq1ba7)!
    *   Looking forward to meeting with us next time? Let us know on Discord or Twitter!

## Acceptance

* [x] Blog post for the hangout (where we can also post updates afterwards) – **DONE: https://frictionlessdata.io/blog/2020/12/17/december-virtual-hangout/**
* [x] Announce on social media + GChat. – **DONE**: Announced on GChat, Twitter and Discord.
* [x] Material prepped re how people can contribute. – **DONE**: We had links for participants to see and we discussed how to improve the experience for contributors during the call.
* [ ] An awesome 🎉 1h community hangout with at least 15 participants. – _Note_: There were up to 11 participants at one point, all of whom introduced themselves and took part actively in the discussions. Christmas is approaching and that may have impacted how well we could reach out the community. Happy holidays to everyone! :tada:

## Tasks

* [x] Zoom call link. – **DONE**: Shared on Discord.
  * [x] Reserve slot in Zoom account. – **DONE**: Meeting created.
  * [x] Email guests ~2-3h before the event with the meeting details. – **DONE**: Guests emailed 2.5 hours before the hangout.
* [x] Announce on Twitter. – **DONE**: https://twitter.com/frictionlessd8a/status/1337092699418193920
* [x] Send reminders on Discord.
  * [x] Send reminder to register a few days / a week before the hangout. – **DONE**: Reminder sent a week before the event.
  * [x] Send meeting link ~10 minutes before the event on Discord. – **DONE**: Reminder sent 10 minutes before the event.
* [x] Announce in GChat (`#Announcements`) a few hours before the hangout. – **DONE**: Announced in the existing thread in `#Announcements`.
* [x] Recording on YouTube.
  * [x] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). – **DONE**: Cleanly cut into two different videos (full + presentation only), removing irrelevant bits (also for privacy concerns for the presenter since personal information was shown on the screen at the beginning of the presentation).
  * [x] Update blog post with link to YouTube video. – **DONE: Videos shown in the blog post https://frictionlessdata.io/blog/2020/12/17/december-virtual-hangout/**
* [x] Material prepped re how people can contribute. – **DONE**: We had links for participants to see and we discussed how to improve the experience for contributors during the call.
* [x] Schedule January meeting. **DONE: Scheduled for January 28th at 2pm GMT. More to come from @sapetti9, the new community manager. :tada:**
* [x] Update RSVP form with the correct hangout date. – **DONE**: Correct date shown.
* [x] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – **DONE**: No Google Meet link showing up.
  * [x] Notify guests by email about the calendar event – click the blue **Send** button when saving the event. – **DONE**: Updated based on answers in the form.
* [x] Create a new entry in the public meeting doc with agenda for this hangout. – **DONE**: New entry created.

**Comment by loleg** [comment]
Sorry for missing tonight's call, sysadmin stuff kept me working late. Hope you had a good chat, and I look forward to catching up via the blog & Discord! I'll be happy to present something in December if you want me to.

**Comment by sglavoie** [comment]
Hi @loleg! No worries at all. We'll be updating the blog, but if you're eager to dive deeper into the technical presentation and/or watch the whole hangout, here you go:

* [Costas S' Table Schema presentation](https://www.youtube.com/watch?v=pJFsJW96fuA)
* [November Frictionless Community Call 2020](https://www.youtube.com/watch?v=ovdGnNYk7cQ)

Of course, you're always welcome to present something and I'm sure we'll have time to go through your updates as we have a presentation that should last roughly up to 30 minutes in the next call. Hopefully let's see each other on December 17, same time (we'll be posting more details as usual) :wink:.

**Comment by sglavoie** [comment]
FIXED: Closing as all tasks were done. More updates to come from @sapetti9, the new community manager! :tada:
