### ISSUE TITLE
Community Call - 28 January 2021

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#578]
Our next 1h community call to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizers: @lwinfree (OKF) & @sapetti9 (OKF) — TBC
Lead of the repo: @lwinfree (OKF)

Date: **28<sup>th</sup> January, 2pm GMT** 

## Agenda (to be added soon)

Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a) and [Discord Channel](https://discordapp.com/invite/Sewv6av)

Join us to hear a presentation from @cpina on schema-collaboration, assists in creating Frictionless data schemas
collaboratively. More information about it here: https://github.com/frictionlessdata/schema-collaboration or here : https://frictionlessdata.io/blog/2020/07/16/tool-fund-polar-institute/ 

RSVP to get the meeting link here: https://forms.gle/k7AsKKD2tu6rm8TR6

## Tasks

* [x] Zoom call link. – 
  * [x] Reserve slot in Zoom account. – 
  * [x] Email guests ~2-3h before the event with the meeting details. – 
* [x] Announce on Twitter. – 
* [x] Send reminders on Discord.
  * [x] Send reminder to register a few days / a week before the hangout. – 
  * [x] Send meeting link ~10 minutes before the event on Discord. – 
* [x] Recording on YouTube. – 
  * [x] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). –
  * [x] Update blog post with link to YouTube video. – 
* [ ] Material prepped re how people can contribute. – 
* [x] Schedule January Zoom meeting. – 
* [x] Update RSVP form with the correct hangout date. – 
* [x] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – 
  * [x] Notify guests by email about the calendar event – click the blue **Send** button when saving the event. –
* [x] Create a new entry in the public meeting doc with agenda for this hangout. –
