### ISSUE TITLE
Merge forum to github discussions in this repo (or to issues if relevant)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#581]
*This is a follow up / replacement to #525 (which was about  merge pre-existence of github discussions).*

In spirit of "one" way to do things if possible, let's move forum (https://github.com/frictionlessdata/forum) stuff to github discussions here (and if there are items that really are issues let's move those).

## Acceptance

* [x] https://github.com/frictionlessdata/forum is deprecated **DONE: See sub-items for details.**
  * [x] Has deprecated style notice in README **DONE: Notice shown here https://github.com/frictionlessdata/forum#the-forum-has-moved-to-github-discussions-httpsgithubcomfrictionlessdataprojectdiscussions**
  * [x] is archived **DONE: Visiting https://github.com/frictionlessdata/forum shows the message `This repository has been archived by the owner. It is now read-only.` at the top of the screen.**
* [x] All items are moved either to discussions here or to an issue here **DONE: All issues were transferred from https://github.com/frictionlessdata/forum/issues to https://github.com/frictionlessdata/project/discussions except #608 #609 #610 which were transferred as issues.**

## Tasks

* [x] Deprecate and archive https://github.com/frictionlessdata/forum **DONE. Add deprecation / redirection to here notice and made repo archived (read-only).**
* [x] Review issues in https://github.com/frictionlessdata/forum and move them to discussions or issues here @sglavoie can you take this one on (?) **DONE: All issues were transferred from https://github.com/frictionlessdata/forum/issues to https://github.com/frictionlessdata/project/discussions except #608 #609 #610 which were transferred as issues.**

## Analysis

---

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by sglavoie** [comment]
Note: I will temporarily unarchive https://github.com/frictionlessdata/forum so I can move issues from that repo to https://github.com/frictionlessdata/project and click on the new option `Convert to discussion` to make a seamless transition.

**Comment by sglavoie** [comment]
FIXED:

* https://github.com/frictionlessdata/forum has been deprecated, see https://github.com/frictionlessdata/forum#the-forum-has-moved-to-github-discussions-httpsgithubcomfrictionlessdataprojectdiscussions and the message `This repository has been archived by the owner. It is now read-only.` at the top of the repo.
* All open issues were transferred from https://github.com/frictionlessdata/forum/issues to https://github.com/frictionlessdata/project/discussions except #608 #609 #610 which were transferred as issues.
