### ISSUE TITLE
Analyse protocol buffers and map types against table schema

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#609]
Protocol buffers is widely used and high quality low level (syntactical) data exchange format from Google.

## Acceptance

* [x] Summary of protocol buffers
* [x] Table of protocol buffer types **https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=0**
* [x] Map of those types to table schema **Ditto**
* [ ] Any relevant code snippets
* [ ] Published somewhere

## Tasks

* [ ] Read up on https://developers.google.com/protocol-buffers

## Analysis

List of core types: https://developers.google.com/protocol-buffers/docs/proto3#scalar

* `repeated` allows for repetition
* `Map` support for dictionaries

See for an extract and mapping to Table Schema: https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=0

- double
- float
- int32
- int64
- uint32
- uint64
- sint32
- sint64
- fixed32
- fixed64
- sfixed32
- sfixed64
- bool
- string
- bytes

**Comment by lwinfree** [comment]
closing as this isn't in the technical roadmap right now. Might be worth looking at in the future!
