### ISSUE TITLE
[epic] Frictionless <=> Other formats

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#610]
Inventory existing data profile and schema formats & compare / mapping against Frictionless.

Done this informally many times over the years. Let's do it systematically and once and for all.

Inventory in progress here: https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=774748003

## Job Stories

When developing or using Frictionless tools for interfacing with format X i want to know how the metadata / schema map so that I can I quickly and reliably do my work

When considering using Frictionless and already familiar with X format I want to know how they compare and how i can map so that I can decide whether to use and how to use

## Acceptance

* [ ] A listing of existing profile and schema formats
* [ ] Key dimensions and attributes for classifying these
* [ ] Mapping of these against Frictionless
* [ ] Write up website somewhere

## Tasks

* [ ] NetCDF frictionlessdata/project#608 
* [ ] Protocol buffer (protobuf) frictionlessdata/project#609 
* [ ] CKAN frictionlessdata/project#574 
* [ ] Project Open Data frictionlessdata/project#584
