### ISSUE TITLE
Configure the Matrix <--> Discord bridge

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/frictionlessdata.io#698]
Users on the Frictionless Discord server can only see and communicate with other users on Discord. Users on the Frictionless Matrix Space can only see and communicate with other users on Matrix. Let's [bridge](https://matrix.org/bridges/) them together.

Following #690 I've created a Matrix Space for Frictionless:

https://matrix.to/#/#frictionless-data:matrix.org

Now we need to bridge the Discord and Matrix together. Some references:

* https://matrix.org/bridges/#discord
* https://t2bot.io/discord/

**What is bridging?**

[Bridges](https://matrix.org/bridges/) allow interoperability between Matrix and other services (like Discord). Anyone using any of the two services can read and write messages to each other. Think of it like mirroring the community, so that anyone can use the tool that suits them best.

## Acceptance

* the community is bridged between Discord and Matrix
* users on any service can see all messages and seamlessly communicate back and forth

## Tasks

* [x] find a suitable Matrix - Discord bridging service – there's a list [here](https://matrix.org/bridges/#discord)
* [x] invite the bot to the Matrix Space
* [x] invite the bot to the Discord server
* [x] configure the bot using whatever steps the documentation says (should be simple)
* [x] check that messages back and forth are going as expected
* [x] bridge the remaining channels

## Analysis

This should enable more people to join the community even if they don't agree to Discord's [controversial](https://herrmann.tech/en/blog/2021/08/10/my-discord-with-discord-or-choosing-alternatives-with-better-terms-of-service.html) terms of service and privacy policy or want to reduce the amount of non-free and open source software they use.

As it turns out, it is not possible to bridge the whole Discord server to a whole Matrix Space. So each channel must be bridged individually.

Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by augusto-herrmann** [comment]
[This bridge bot](https://t2bot.io/discord/) seems good enough. It is the first one in the list. [Its code](https://github.com/Half-Shot/matrix-appservice-discord) is also on Github and open source, but let's just use the hosted version.

**Comment by augusto-herrmann** [comment]
I have already invited it to the Matrix Space and it's already there. Now we need to follow through with steps 2-4 (instructions are [here](https://t2bot.io/discord/), and for that I need someone with access to the Discord server:

> 2. Use [this link](https://discordapp.com/api/oauth2/authorize?client_id=309408702530846730&scope=bot&permissions=607251456) to invite the bridge to your Discord server.
> 3. Open the text channel (voice isn't supported yet) in the Discord web application.
> 4. In the address bar there should be a URL like https://discordapp.com/channels/ServerID/ChannelID - use that as a reference to say in your Matrix room !discord bridge ServerID ChannelID.

For step 4, just tell me the ServerID and I'll add it in Matrix. I'm not sure whether it's possible to bridge the entire Discord server to the Matrix Space, or if I'll need to do this channel by channel. In the latter case, I would appreciate if at least we could do the #Hackathon-general channel for now and leave the rest for later when we have the time.

**Comment by augusto-herrmann** [comment]
It works!

Anyone who would like to experiment is welcome to join the Matrix Space at:

https://matrix.to/#/#frictionless-data:matrix.org

For now, only the `#general` and `#Hackathon-general` are linked, but we should bridge the rest of them soon.

**Comment by augusto-herrmann** [comment]
I think we're done with this. Yay! :tada: Thank you for doing this together, @lwinfree!

**Comment by Evidlo** [comment]
Can this be linked on the website somewhere?  I wasn't aware there was a Matrix room until I saw the bridge bot on Discord.

**Comment by augusto-herrmann** [comment]
Thanks for the heads up, @Evidlo ! I've now created an issue for it in the website repository.
