### ISSUE TITLE
Community Call on 16 December

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#703]
Our next 1h community call to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizers: @lwinfree (OKF) & @sapetti9 (OKF) 
Lead of the repo: @lwinfree (OKF)

Date: **16<sup>th</sup> December, 3 pm CET** 

## Agenda 

Join us to hear Keith Hughit present some ideas around representing data processing flows as a DAG inside of a datapackage.json, and tools for interacting with and visualizing such DAGs.

RSVP to get the meeting link here: https://forms.gle/k7AsKKD2tu6rm8TR6

Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a) and [Discord Channel](https://discordapp.com/invite/Sewv6av)

## Tasks

* [ ] Zoom call link. – 
  * [x] Reserve slot in Zoom account. – 
  * [ ] Email guests ~2-3h before the event with the meeting details. – 
* [x] Announce on Twitter. – 
* [x] Send reminders on Discord.
  * [x] Send reminder to register a few days / a week before the hangout. – 
  * [ ] Send meeting link ~10 minutes before the event on Discord. – 
* [ ] Recording on YouTube. – 
  * [ ] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). –
  * [ ] Update blog post with link to YouTube video. – 
* [ ] Schedule January Zoom meeting. – 
* [ ] Update RSVP form with the correct hangout date. – 
* [ ] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – 
  * [ ] Notify guests by email about the calendar event – click the blue **Send** button when saving the event. –
* [ ] Create a new entry in the public meeting doc with agenda for this hangout. –

**Comment by roll** [comment]
DONE
