### ISSUE TITLE
NEW DATE - Community Call 27 October

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#755]
Our next 1h community call to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizer: @sapetti9 (OKF) 

Date: **27<sup>th</sup> October, 4 pm CEST**
**Please note this call is one hour later than usual.**

## Agenda 

This month we will hear a presentation on the Frictionless - Zenodo integration from Frictionless Data developer @shashigharti.
RSVP to get the meeting link here: https://forms.gle/k7AsKKD2tu6rm8TR6

Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a), [Slack Community chat](https://frictionlessdata.slack.com/messages/general), [Matrix bridge](https://matrix.to/#/#frictionlessdata:matrix.okfn.org)

## Tasks

* [x] Zoom call link. – 
  * [x] Reserve slot in Zoom account. – 
  * [x] Email guests ~2-3h before the event with the meeting details. – 
* [x] Announce on Twitter. – 
* [x] Send reminders on Slack.
  * [x] Send reminder to register a few days / a week before the hangout. – 
  * [x] Send meeting link ~10 minutes before the event on Slack. – 
* [x] Recording on YouTube. – 
  * [x] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). –
  * [ ] Update blog post with link to YouTube video. – 
* [x] Update RSVP form with the correct date. – 
* [x] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – 
  * [x] Notify guests by email about the calendar event – click the blue **Send** button when saving the event. –
* [x] Create a new entry in the public meeting doc with agenda for this hangout. –

**Comment by sapetti9** [comment]
WARNING! This community call is canceled. The presentation of the Frictionless Framework v5 is moved to October 27th, at 4pm CEST.

**Comment by sapetti9** [comment]
Update: the presentation of the Framework v5 is postponed. At the October community call we will hear about the Zenodo integration.
