### ISSUE TITLE
Community Call 1 December

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#772]
Our next 1h community call to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizer: @sapetti9 (OKF) 

Date: **1<sup>st</sup> December, 4 pm CEST**
**Please note this call is one hour later than usual.**

## Agenda 

This month's presentation is TBC. 

RSVP to get the meeting link here: https://forms.gle/k7AsKKD2tu6rm8TR6

Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a), [Slack Community chat](https://frictionlessdata.slack.com/messages/general), [Matrix bridge](https://matrix.to/#/#frictionlessdata:matrix.okfn.org)

## Tasks

* [x] Zoom call link. – 
  * [x] Reserve slot in Zoom account. – 
  * [x] Email guests ~2-3h before the event with the meeting details. – 
* [x] Announce on Twitter. – 
* [x] Send reminders on Slack.
  * [x] Send reminder to register a few days / a week before the call. – 
  * [x] Send meeting link ~10 minutes before the event on Slack. – 
* [x] Recording on YouTube. – 
  * [x] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). –
  * [x] Update blog post with link to YouTube video. – 
* [x] Update RSVP form with the correct date. – 
* [x] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – 
  * [x] Notify guests by email about the calendar event –
* [x] Create a new entry in the public meeting doc with agenda for this call. –

**Comment by sapetti9** [comment]
Blog: https://github.com/frictionlessdata/frictionlessdata.io/pull/779
