### ISSUE TITLE
Next community call May 25th

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#810]
Our next 1h community call to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizer: @sapetti9 (OKFN) 

Date: **25<sup>th</sup> May, 4 pm CEST**

## Agenda 

This month we will hear from Augusto Herrmann about FastETL, a free and open source software library that makes it easier to integrate heterogeneous data sources and to publish open data. Augusto will tell us how to use it with the Frictionless Framework & Tabular Data Package to process data pipelines and to publish open data.

RSVP to get the meeting link here: https://forms.gle/k7AsKKD2tu6rm8TR6

Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a), [Slack Community chat](https://frictionlessdata.slack.com/messages/general), [Matrix bridge](https://matrix.to/#/#frictionlessdata:matrix.okfn.org)

## Tasks

* [x] Zoom call link. – 
  * [x] Reserve slot in Zoom account. – 
  * [x] Email guests ~2-3h before the event with the meeting details. – 
* [x] Announce on Twitter. – 
* [x] Send reminders on Slack.
  * [x] Send reminder to register a few days / a week before the call. – 
  * [x] Send meeting link ~10 minutes before the event on Slack. – 
* [x] Recording on YouTube. – 
  * [x] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). –
  * [x] Update blog post with link to YouTube video. – 
* [x] Update RSVP form with the correct date. – 
* [x] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – 
  * [x] Notify guests by email about the calendar event –
* [x] Create a new entry in the public meeting doc with agenda for this call. –

**Comment by sapetti9** [comment]
Waiting for review & merge of linked PRs to close this.
