### ISSUE TITLE
[CANCELED]Next community call August 31st

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#821]
Our next 1h community call to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizer: @sapetti9 (OKFN) 

~~Date: **31<sup>st</sup> August, 4 pm CEST**~~

**The August community call is canceled. See you all on September 28th.**

## Agenda 

TBC. If you would like to present something, please let us know.

RSVP to get the meeting link here: https://forms.gle/k7AsKKD2tu6rm8TR6

Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a), [Slack Community chat](https://frictionlessdata.slack.com/messages/general), [Matrix bridge](https://matrix.to/#/#frictionlessdata:matrix.okfn.org)

## Tasks

* [ ] Zoom call link. – 
  * [ ] Reserve slot in Zoom account. – 
  * [ ] Email guests ~2-3h before the event with the meeting details. – 
* [ ] Announce on Twitter. – 
* [ ] Send reminders on Slack.
  * [ ] Send reminder to register a few days / a week before the call. – 
  * [ ] Send meeting link ~10 minutes before the event on Slack. – 
* [ ] Recording on YouTube. – 
  * [ ] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). –
  * [ ] Update blog post with link to YouTube video. – 
* [ ] Update RSVP form with the correct date. – 
* [ ] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – 
  * [ ] Notify guests by email about the calendar event –
* [ ] Create a new entry in the public meeting doc with agenda for this call. –
