### ISSUE TITLE
What happened to dataprotocols.org stuff (and can we archive it somewhere!)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionlessdata.io#872]
I thought that non FD stuff from dataprotocols.org got migrated somewhere but i can't find it online ... and when i search for e.g. revisioning summary the only source i find is http://paulfitz.github.io/dataprotocols/revisioning-data/index.html

Context

* dataprotocols.org was the original site for what are now the frictionless data specs.
* At some point these moved to specs.frictionlessdata.io.
* OKF team (Dan) then (2017?) subsequently split out some of the less data package-y stuff and move it to https://github.com/okfn/specs which is supposed to be live at http://specs.okfnlabs.org/ but which is now (as of 2019) broken.

### Solutions

IMO (Rufus) some of dataprotocols.org stuff is still relevant. There seem 2 options:

* One site of specs (so we merge back into FD specs list)
* 2 sites for specs e.g. FD specs and specs.okfnlabs.org (or dataprotocols.org)

I actually have a slight preference for 1 - why split stuff up. If we need to be clear on data package suite of specs we can do that but the line is not always hard and fast (e.g. units specs should really be in FD rather than somewhere else as it is atm).

Either way if would be nice to have proper redirects for dataprotocols.org so it works - see frictionlessdata/project#362 (or put up an archive copy of dataprotocols.org (specs.okfnlabs.org not working!))

## Tasks

* [ ] Decide what we are doing
* [ ] Do it ... 
* [ ] daff reconnected frictionlessdata/project#361 
* [ ] improve dataprotocols.org redirect frictionlessdata/project#362
