### ISSUE TITLE
Next Community Call: May 30th!

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#911]
Our next 1h community call to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizer: @sapetti9 (OKFN) 

Date: **30<sup>th</sup> May, 4 pm CEST**

## Agenda 

Update on the [Frictionless specs](https://specs.frictionlessdata.io/) review. Let's discuss!

RSVP to get the meeting link here: https://forms.gle/k7AsKKD2tu6rm8TR6

Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a), [Slack Community chat](https://frictionlessdata.slack.com/messages/general), [Matrix bridge](https://matrix.to/#/#frictionlessdata:matrix.okfn.org)

## Tasks

* [x] Zoom call link. – 
  * [x] Reserve slot in Zoom account. – 
  * [x] Email guests ~2-3h before the event with the meeting details. – 
* [x] Announce on Twitter. – 
* [x] Send reminders on Slack.
  * [x] Send reminder to register a few days / a week before the call. – 
  * [x] Send meeting link ~10 minutes before the event on Slack. – 
* [x] Recording on YouTube. – 
  * [ ] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). –
  * [ ] Update blog post with link to YouTube video. – 
* [x] Update RSVP form with the correct date. – 
* [x] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – 
  * [ ] Notify guests by email about the calendar event –
* [ ] Create a new entry in the public meeting doc with agenda for this call. –

**Comment by neolefty** [comment]
Is this still happening today? I'm down to meet — am part of a team that wants to get started contributing.

**Comment by sapetti9** [comment]
Hi @neolefty, I am sorry I am seeing this message only now. The call did happen, but 2 hours ago. Please sign up here: https://forms.gle/vUSBAvkP795v2kLV6 so I can invite you to the next calls.

**Comment by neolefty** [comment]
I was so ready! But never received a link, despite registering yesterday. Okay I'll try again next month.

**Comment by neolefty** [comment]
I registered for this meeting using the previous Google form (linked in the issue) and checked "inform me of future meetups" — should I re-register for the next one?

**Comment by sapetti9** [comment]
No, then you are in. Weird that you did not receive the invitation for today's talk. I'll have a look.
