### ISSUE TITLE
Next community call: June 20th

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/frictionlessdata.io#916]
Our next 1,5h community call to chat about recent developments in Frictionless and data generally and next steps, involving our community members in the process!

Organizer: @sapetti9 (OKFN) 

Date: **20<sup>th</sup> June, 4 pm CEST**
Please note this call will be on the 3rd Thursday of the month (instead of the last one) and will be 30 mins longer than usual.

## Agenda 

This is the last working group call on on the [Frictionless standards](https://frictionlessdata.io/blog/2023/11/15/frictionless-specs-update/) review. We will use the call to review the [documentation](https://datapackage.org/).

RSVP to get the meeting link here: https://forms.gle/k7AsKKD2tu6rm8TR6

Social Media [@Frictionlessd8a](https://twitter.com/Frictionlessd8a), [Slack Community chat](https://frictionlessdata.slack.com/messages/general), [Matrix bridge](https://matrix.to/#/#frictionlessdata:matrix.okfn.org)

## Tasks

* [x] Zoom call link. – 
  * [x] Reserve slot in Zoom account. – 
  * [x] Email guests ~2-3h before the event with the meeting details. – 
* [x] Announce on Twitter. – 
* [x] Send reminders on Slack.
  * [x] Send reminder to register a few days / a week before the call. – 
  * [x] Send meeting link ~10 minutes before the event on Slack. – 
* [x] Recording on YouTube. – 
  * [ ] Process video(s) (cut presentation out as a separate video if any, trim beginning and end if necessary). –
  * [ ] Update blog post with link to YouTube video. – 
* [x] Update RSVP form with the correct date. – 
* [x] Add previous guests to the Google Calendar invite (make sure Google Meet is turned off!). – 
  * [x] Notify guests by email about the calendar event –
* [x] Create a new entry in the public meeting doc with agenda for this call. –

**Comment by sapetti9** [comment]
Leaving this open as I still need to write the blog recap of the call for https://frictionlessdata.io/blog/
